Repository WISE-Community/WISE-Client, pull requests merged in 2021-07, with the labels that each got.

#236 Upgraded WorkgroupComponentGrading to Angular
  src/app/teacher-hybrid-angular.module.ts
  src/assets/wise5/classroomMonitor/classroomMonitorComponents/milestones/milestoneWorkgroupItem/milestoneWorkgroupItem.html
  src/assets/wise5/classroomMonitor/classroomMonitorComponents/nodeGrading/workgroupItem/workgroupItem.ts
  src/assets/wise5/classroomMonitor/classroomMonitorComponents/shared/shared.ts
  src/assets/wise5/classroomMonitor/classroomMonitorComponents/shared/workgroupComponentGrading/workgroupComponentGrading.html
  src/assets/wise5/classroomMonitor/classroomMonitorComponents/shared/workgroupComponentGrading/workgroupComponentGrading.ts
  src/assets/wise5/classroomMonitor/classroomMonitorComponents/studentGrading/stepItem/stepItem.ts
  src/assets/wise5/classroomMonitor/classroomMonitorComponents/view-component-revisions/view-component-revisions.component.html
  src/assets/wise5/classroomMonitor/classroomMonitorComponents/view-component-revisions/view-component-revisions.component.ts
  src/assets/wise5/classroomMonitor/classroomMonitorComponents/workgroup-component-grading/workgroup-component-grading.component.html
  src/assets/wise5/classroomMonitor/classroomMonitorComponents/workgroup-component-grading/workgroup-component-grading.component.ts
  src/assets/wise5/components/component-grading.module.ts
  src/messages.xlf
Labels: 1 point

#239 Upgraded PeriodSelect to Angular
  src/app/teacher-hybrid-angular.module.ts
  src/assets/wise5/classroomMonitor/classroomMonitorComponents/milestones/milestoneDetails/milestoneDetails.ts
  src/assets/wise5/classroomMonitor/classroomMonitorComponents/select-period/select-period.component.html
  src/assets/wise5/classroomMonitor/classroomMonitorComponents/select-period/select-period.component.scss
  src/assets/wise5/classroomMonitor/classroomMonitorComponents/select-period/select-period.component.ts
  src/assets/wise5/classroomMonitor/classroomMonitorComponents/shared/periodSelect/periodSelect.ts
  src/assets/wise5/classroomMonitor/classroomMonitorComponents/shared/shared.ts
  src/assets/wise5/classroomMonitor/classroomMonitorComponents/shared/toolbar/toolbar.ts
  src/assets/wise5/components/component-grading.module.ts
  src/messages.xlf
Labels: 1 point

#240 Convert Table student component to Angular
  src/app/student-hybrid-angular.module.ts
  src/assets/wise5/authoringTool/components/preview-component/previewComponent.ts
  src/assets/wise5/components/component-student.component.ts
  src/assets/wise5/components/conceptMap/concept-map-student/concept-map-student.component.ts
  src/assets/wise5/components/table/index.html
  src/assets/wise5/components/table/table-student/table-student.component.html
  src/assets/wise5/components/table/table-student/table-student.component.scss
  src/assets/wise5/components/table/table-student/table-student.component.spec.ts
  src/assets/wise5/components/table/table-student/table-student.component.ts
  src/assets/wise5/components/table/tableComponentModule.ts
  src/assets/wise5/components/table/tableService.ts
  src/assets/wise5/directives/component/component.ts
  src/assets/wise5/vle/node/nodeController.ts
  src/assets/wise5/vle/studentAsset/studentAssetController.ts
  src/messages.xlf
Labels: 1 point

#244 Split teacher-hybrid-angular into AT and CM
  src/app/common-hybrid-angular.module.ts
  src/app/student-hybrid-angular.module.ts
  src/app/teacher-hybrid-angular.module.ts
  src/app/teacher/authoring-tool.module.ts
  src/app/teacher/classroom-monitor.module.ts
  src/app/teacher/component-authoring.module.ts
  src/app/teacher/component-grading.module.ts
Labels: 1 point

#248 Extracted delete/move node and copy project functions
  src/app/services/deleteNodeService.spec.ts
  src/app/services/projectService.spec.ts
  src/app/services/teacherProjectService.spec.ts
  src/app/teacher-hybrid-angular.module.ts
  src/assets/wise5/authoringTool/main/mainAuthoringComponent.ts
  src/assets/wise5/authoringTool/project/projectAuthoringComponent.ts
  src/assets/wise5/services/copyProjectService.ts
  src/assets/wise5/services/deleteNodeService.ts
  src/assets/wise5/services/moveNodesService.ts
  src/assets/wise5/services/teacherProjectService.ts
  src/assets/wise5/teacher/teacher-angular-js-module.ts
  src/messages.xlf
Labels: 1 point

#250 Manage students display workgroups
  src/app/teacher/classroom-monitor.module.ts
  src/assets/wise5/classroomMonitor/classroomMonitorComponents/manageStudents/manage-period/manage-period.component.html
  src/assets/wise5/classroomMonitor/classroomMonitorComponents/manageStudents/manage-period/manage-period.component.scss
  src/assets/wise5/classroomMonitor/classroomMonitorComponents/manageStudents/manage-period/manage-period.component.spec.ts
  src/assets/wise5/classroomMonitor/classroomMonitorComponents/manageStudents/manage-period/manage-period.component.ts
  src/assets/wise5/classroomMonitor/classroomMonitorComponents/manageStudents/manage-students/manage-students.component.html
  src/assets/wise5/classroomMonitor/classroomMonitorComponents/manageStudents/manage-students/manage-students.component.ts
  src/assets/wise5/classroomMonitor/classroomMonitorComponents/manageStudents/manage-team/manage-team.component.html
  src/assets/wise5/classroomMonitor/classroomMonitorComponents/manageStudents/manage-team/manage-team.component.scss
  src/assets/wise5/classroomMonitor/classroomMonitorComponents/manageStudents/manage-team/manage-team.component.ts
  src/assets/wise5/classroomMonitor/classroomMonitorComponents/manageStudents/manage-user/manage-user.component.html
  src/assets/wise5/classroomMonitor/classroomMonitorComponents/manageStudents/manage-user/manage-user.component.ts
  src/assets/wise5/classroomMonitor/classroomMonitorComponents/manageStudents/manageStudentsModule.ts
  src/assets/wise5/classroomMonitor/classroomMonitorController.ts
  src/assets/wise5/classroomMonitor/manageStudents/manage-students-legacy.component.ts
  src/assets/wise5/classroomMonitor/manageStudents/manage-students-legacy.html
  src/messages.xlf
Labels: 1 point

#252 Extracted CopyComponentService from TeacherProjectService
  src/app/services/copyComponentService.spec.ts
  src/app/services/insertComponentService.spec.ts
  src/app/teacher-hybrid-angular.module.ts
  src/assets/wise5/authoringTool/node/nodeAuthoringComponent.ts
  src/assets/wise5/services/copyComponentService.ts
  src/assets/wise5/services/insertComponentService.ts
  src/assets/wise5/services/teacherProjectService.ts
  src/assets/wise5/teacher/teacher-angular-js-module.ts
Labels: 1 point

#254 Extract importComponents into its own service
  src/app/teacher-hybrid-angular.module.ts
  src/assets/wise5/authoringTool/importComponent/choose-component-location.component.ts
  src/assets/wise5/services/importComponentService.ts
  src/assets/wise5/services/teacherProjectService.ts
  src/assets/wise5/teacher/teacher-angular-js-module.ts
Labels: 1 point

#222 Show latest posts from Discourse news category on site home
  src/app/discourse-feed/discourse-feed.component.spec.ts
  src/app/discourse-feed/discourse-feed.component.ts
  src/app/home/discourse-latest-news/discourse-latest-news.component.html
  src/app/home/discourse-latest-news/discourse-latest-news.component.scss
  src/app/home/discourse-latest-news/discourse-latest-news.component.ts
  src/app/home/home.component.html
  src/app/home/home.component.scss
  src/app/home/home.component.ts
  src/app/home/home.module.ts
  src/app/modules/footer/footer.component.html
  src/app/modules/header/header-links/header-links.component.html
  src/app/modules/mobile-menu/mobile-menu.component.html
  src/app/modules/shared/call-to-action/call-to-action.component.html
  src/app/modules/shared/call-to-action/call-to-action.component.scss
  src/app/modules/shared/hero-section/hero-section.component.html
  src/app/modules/shared/hero-section/hero-section.component.scss
  src/app/modules/shared/hero-section/hero-section.component.ts
  src/app/teacher/discourse-recent-activity/discourse-recent-activity.component.html
  src/app/teacher/discourse-recent-activity/discourse-recent-activity.component.spec.ts
  src/app/teacher/discourse-recent-activity/discourse-recent-activity.component.ts
  src/app/teacher/teacher-home/teacher-home.component.html
  src/app/teacher/teacher-home/teacher-home.component.spec.ts
  src/app/teacher/teacher-home/teacher-home.component.ts
  src/messages.xlf
  src/style/abstracts/_mixins.scss
Labels: 1 point

#258 Moved copyNodesInside/After and copyNode functions
  src/app/services/copyNodesService.spec.ts
  src/app/services/teacherProjectService.spec.ts
  src/assets/wise5/authoringTool/project/projectAuthoringComponent.ts
  src/assets/wise5/services/copyNodesService.ts
  src/assets/wise5/services/teacherProjectService.ts
  src/assets/wise5/teacher/teacher-angular-js-module.ts
Labels: 1 point

#255 Convert Summary student component to Angular
  src/app/student-hybrid-angular.module.ts
  src/assets/wise5/authoringTool/components/preview-component/previewComponent.ts
  src/assets/wise5/classroomMonitor/classroomMonitorComponents/shared/nodeInfo/nodeInfo.ts
  src/assets/wise5/components/summary/index.html
  src/assets/wise5/components/summary/summary-student/summary-student.component.html
  src/assets/wise5/components/summary/summary-student/summary-student.component.scss
  src/assets/wise5/components/summary/summary-student/summary-student.component.spec.ts
  src/assets/wise5/components/summary/summary-student/summary-student.component.ts
  src/assets/wise5/components/summary/summaryComponentModule.ts
  src/assets/wise5/directives/component/component.ts
  src/assets/wise5/directives/components.ts
  src/assets/wise5/directives/summaryDisplay/summary-display.component.html
  src/assets/wise5/directives/summaryDisplay/summary-display.component.scss
  src/assets/wise5/directives/summaryDisplay/summary-display.component.spec.ts
  src/assets/wise5/directives/summaryDisplay/summary-display.component.ts
  src/assets/wise5/directives/summaryDisplay/summaryDisplay.html
  src/assets/wise5/vle/node/nodeController.ts
  src/messages.xlf
Labels: 1 point

#259 ManageStudentsRewrite: implemented change period dialog
  src/app/teacher/classroom-monitor.module.ts
  src/assets/wise5/classroomMonitor/classroomMonitorComponents/manageStudents/change-team-period-dialog/change-team-period-dialog.component.html
  src/assets/wise5/classroomMonitor/classroomMonitorComponents/manageStudents/change-team-period-dialog/change-team-period-dialog.component.scss
  src/assets/wise5/classroomMonitor/classroomMonitorComponents/manageStudents/change-team-period-dialog/change-team-period-dialog.component.spec.ts
  src/assets/wise5/classroomMonitor/classroomMonitorComponents/manageStudents/change-team-period-dialog/change-team-period-dialog.component.ts
  src/assets/wise5/classroomMonitor/classroomMonitorComponents/manageStudents/manage-period/manage-period.component.html
  src/assets/wise5/classroomMonitor/classroomMonitorComponents/manageStudents/manage-period/manage-period.component.ts
  src/assets/wise5/classroomMonitor/classroomMonitorComponents/manageStudents/manage-team/manage-team.component.html
  src/assets/wise5/classroomMonitor/classroomMonitorComponents/manageStudents/manage-team/manage-team.component.spec.ts
  src/assets/wise5/classroomMonitor/classroomMonitorComponents/manageStudents/manage-team/manage-team.component.ts
  src/assets/wise5/classroomMonitor/classroomMonitorComponents/manageStudents/manage-user/manage-user.component.html
  src/assets/wise5/classroomMonitor/classroomMonitorComponents/manageStudents/manage-user/manage-user.component.spec.ts
  src/assets/wise5/classroomMonitor/classroomMonitorComponents/manageStudents/manage-user/manage-user.component.ts
  src/assets/wise5/services/configService.ts
  src/messages.xlf
Labels: 2 points

#266 TAP report show before after responses
  src/assets/wise5/classroomMonitor/classroomMonitorComponents/milestones/milestoneGradingView/milestoneGradingView.html
  src/assets/wise5/classroomMonitor/classroomMonitorComponents/milestones/milestoneGradingView/milestoneGradingView.ts
  src/assets/wise5/classroomMonitor/classroomMonitorComponents/milestones/milestoneWorkgroupItem/milestoneWorkgroupItem.html
  src/assets/wise5/classroomMonitor/classroomMonitorComponents/milestones/milestoneWorkgroupItem/milestoneWorkgroupItem.ts
  src/assets/wise5/classroomMonitor/classroomMonitorComponents/nodeGrading/nodeGradingView/nodeGradingView.ts
  src/assets/wise5/classroomMonitor/i18n/i18n_en.json
  src/assets/wise5/i18n/i18n_en.json
Labels: 2 points

#268 Show Multiple Choice image choices in export
  src/app/services/utilService.spec.ts
  src/assets/wise5/services/utilService.ts
Labels: 1 point

#261 Convert Discussion student component to Angular
  src/app/student-hybrid-angular.module.ts
  src/assets/wise5/authoringTool/components/preview-component/previewComponent.ts
  src/assets/wise5/components/component-student.component.ts
  src/assets/wise5/components/discussion/discussion-student/discussion-student.component.html
  src/assets/wise5/components/discussion/discussion-student/discussion-student.component.scss
  src/assets/wise5/components/discussion/discussion-student/discussion-student.component.spec.ts
  src/assets/wise5/components/discussion/discussion-student/discussion-student.component.ts
  src/assets/wise5/components/discussion/discussionComponentModule.ts
  src/assets/wise5/components/discussion/index.html
  src/assets/wise5/directives/component/component.ts
  src/assets/wise5/vle/node/nodeController.ts
  src/messages.xlf
Labels: 1 point

#269 Manage students move members
  src/app/services/getWorkgroupService.ts
  src/app/services/updateWorkgroupService.ts
  src/app/teacher-hybrid-angular.module.ts
  src/app/teacher/classroom-monitor.module.ts
  src/assets/wise5/classroomMonitor/classroomMonitorComponents/manageStudents/manage-period/manage-period.component.html
  src/assets/wise5/classroomMonitor/classroomMonitorComponents/manageStudents/manage-period/manage-period.component.spec.ts
  src/assets/wise5/classroomMonitor/classroomMonitorComponents/manageStudents/manage-period/manage-period.component.ts
  src/assets/wise5/classroomMonitor/classroomMonitorComponents/manageStudents/manage-team/manage-team.component.html
  src/assets/wise5/classroomMonitor/classroomMonitorComponents/manageStudents/manage-team/manage-team.component.scss
  src/assets/wise5/classroomMonitor/classroomMonitorComponents/manageStudents/manage-team/manage-team.component.spec.ts
  src/assets/wise5/classroomMonitor/classroomMonitorComponents/manageStudents/manage-team/manage-team.component.ts
  src/assets/wise5/classroomMonitor/classroomMonitorComponents/manageStudents/manageStudentsModule.ts
  src/assets/wise5/classroomMonitor/classroomMonitorComponents/manageStudents/move-user-confirm-dialog/move-user-confirm-dialog.component.html
  src/assets/wise5/classroomMonitor/classroomMonitorComponents/manageStudents/move-user-confirm-dialog/move-user-confirm-dialog.component.spec.ts
  src/assets/wise5/classroomMonitor/classroomMonitorComponents/manageStudents/move-user-confirm-dialog/move-user-confirm-dialog.component.ts
Labels: 2 points

#272 Fixed manage students period select dropdown updating issues
  src/app/services/sampleData/sample_classmateUserInfos.json
  src/app/services/workgroup.service.spec.ts
  src/app/services/workgroup.service.ts
  src/app/teacher-hybrid-angular.module.ts
  src/assets/wise5/classroomMonitor/classroomMonitorComponents/manageStudents/manage-period/manage-period.component.html
  src/assets/wise5/classroomMonitor/classroomMonitorComponents/manageStudents/manage-period/manage-period.component.spec.ts
  src/assets/wise5/classroomMonitor/classroomMonitorComponents/manageStudents/manage-period/manage-period.component.ts
  src/assets/wise5/classroomMonitor/classroomMonitorComponents/manageStudents/manage-team/manage-team.component.html
  src/assets/wise5/classroomMonitor/classroomMonitorComponents/manageStudents/manage-team/manage-team.component.spec.ts
  src/assets/wise5/classroomMonitor/classroomMonitorComponents/select-period/select-period.component.html
  src/assets/wise5/classroomMonitor/classroomMonitorComponents/select-period/select-period.component.ts
  src/assets/wise5/services/teacherDataService.ts
  src/messages.xlf
Labels: 1 point

#275 Authoring Tool previous and next buttons are disabled after adding a step
  src/assets/wise5/authoringTool/project/projectAuthoringComponent.ts
Labels: 1 point

#280 Import Draw into Concept Map sometimes does not work
  src/assets/wise5/components/conceptMap/concept-map-student/concept-map-student.component.html
  src/assets/wise5/components/conceptMap/concept-map-student/concept-map-student.component.ts
  src/assets/wise5/components/draw/draw-student/draw-student.component.spec.ts
  src/assets/wise5/components/draw/draw-student/draw-student.component.ts
Labels: 1 point

#281 Manage student show info
  src/app/teacher/classroom-monitor.module.ts
  src/assets/wise5/classroomMonitor/classroomMonitorComponents/manageStudents/manage-show-student-info/manage-show-student-info.component.html
  src/assets/wise5/classroomMonitor/classroomMonitorComponents/manageStudents/manage-show-student-info/manage-show-student-info.component.spec.ts
  src/assets/wise5/classroomMonitor/classroomMonitorComponents/manageStudents/manage-show-student-info/manage-show-student-info.component.ts
  src/assets/wise5/classroomMonitor/classroomMonitorComponents/manageStudents/manage-user/manage-user.component.html
  src/assets/wise5/classroomMonitor/classroomMonitorComponents/manageStudents/manage-user/manage-user.component.spec.ts
  src/assets/wise5/classroomMonitor/classroomMonitorComponents/manageStudents/manage-user/manage-user.component.ts
  src/messages.xlf
Labels: 4 points

#273 Convert Graph student component to Angular
  src/app/student-hybrid-angular.module.ts
  src/assets/wise5/authoringTool/components/preview-component/previewComponent.ts
  src/assets/wise5/components/graph/graph-student/graph-student.component.html
  src/assets/wise5/components/graph/graph-student/graph-student.component.scss
  src/assets/wise5/components/graph/graph-student/graph-student.component.spec.ts
  src/assets/wise5/components/graph/graph-student/graph-student.component.ts
  src/assets/wise5/components/graph/graphComponentModule.ts
  src/assets/wise5/components/graph/index.html
  src/assets/wise5/directives/component/component.ts
  src/assets/wise5/vle/node/nodeController.ts
  src/messages.xlf
Labels: 1 point
