Repository WISE-Community/WISE-Client, pull requests merged in 2021-04, with the labels that each got.

#33 Added before/after scores and change in score column to Milestone report Student Work displays
  src/assets/wise5/classroomMonitor/classroomMonitorComponents/milestones/milestoneGradingView/milestoneGradingView.html
  src/assets/wise5/classroomMonitor/classroomMonitorComponents/milestones/milestoneGradingView/milestoneGradingView.ts
  src/assets/wise5/classroomMonitor/classroomMonitorComponents/milestones/milestoneWorkgroupItem/milestoneWorkgroupItem.html
  src/assets/wise5/classroomMonitor/classroomMonitorComponents/milestones/milestoneWorkgroupItem/milestoneWorkgroupItem.ts
  src/assets/wise5/classroomMonitor/classroomMonitorComponents/nodeGrading/nodeGrading.ts
  src/assets/wise5/classroomMonitor/classroomMonitorComponents/nodeGrading/workgroupItem/workgroupItem.ts
  src/assets/wise5/classroomMonitor/i18n/i18n_en.json
Labels: 1 point

#32 Cleaned up NavItem.ts
  src/assets/wise5/classroomMonitor/classroomMonitorComponents/nodeProgress/navItem/navItem.html
  src/assets/wise5/classroomMonitor/classroomMonitorComponents/nodeProgress/navItem/navItem.ts
Labels: 1 point

#35 Convert authoring main, project, and node controllers into components
  src/assets/wise5/authoringTool/main/mainAuthoring.html
  src/assets/wise5/authoringTool/main/mainAuthoringComponent.ts
  src/assets/wise5/authoringTool/node/node.html
  src/assets/wise5/authoringTool/node/nodeAuthoring.html
  src/assets/wise5/authoringTool/node/nodeAuthoringComponent.ts
  src/assets/wise5/authoringTool/project/projectAuthoring.html
  src/assets/wise5/authoringTool/project/projectAuthoringComponent.ts
  src/assets/wise5/teacher/teacher-angular-js-module.ts
Labels: 1 point

#37 Clean up remaining grading mode checks
  src/assets/wise5/classroomMonitor/classroomMonitorComponents/shared/workgroupComponentGrading/workgroupComponentGrading.html
  src/assets/wise5/classroomMonitor/classroomMonitorComponents/shared/workgroupComponentRevisions/workgroupComponentRevisions.ts
  src/assets/wise5/components/componentController.ts
  src/assets/wise5/components/conceptMap/conceptMapController.ts
  src/assets/wise5/components/discussion/discussionController.ts
  src/assets/wise5/components/graph/graphController.ts
  src/assets/wise5/components/graph/index.html
Labels: 1 point

#39 Converted remaining AT controllers into components
  src/app/authoring-tool/edit-component-json/edit-component-json.component.ts
  src/app/services/projectAssetService.ts
  src/assets/wise5/authoringTool/asset/asset.html
  src/assets/wise5/authoringTool/asset/assetAuthoring.html
  src/assets/wise5/authoringTool/asset/projectAssetAuthoringComponent.ts
  src/assets/wise5/authoringTool/authoringTool.html
  src/assets/wise5/authoringTool/authoringToolComponent.ts
  src/assets/wise5/authoringTool/info/info.html
  src/assets/wise5/authoringTool/info/infoAuthoring.html
  src/assets/wise5/authoringTool/info/projectInfoAuthoringComponent.ts
  src/assets/wise5/authoringTool/milestones/milestonesAuthoring.html
  src/assets/wise5/authoringTool/milestones/milestonesAuthoringComponent.ts
  src/assets/wise5/authoringTool/notebook/notebookAuthoring.html
  src/assets/wise5/authoringTool/notebook/notebookAuthoringComponent.ts
  src/assets/wise5/authoringTool/wiseLink/wiseLinkAuthoring.html
  src/assets/wise5/services/teacherProjectService.ts
  src/assets/wise5/teacher/teacher-angular-js-module.ts
Labels: 1 point

#42 Issue replying to Discussion posts in Preview mode
  src/assets/wise5/classroomMonitor/classroomMonitorComponents/shared/componentGrading/componentGrading.ts
  src/assets/wise5/components/componentController.ts
  src/assets/wise5/components/discussion/discussionController.ts
  src/assets/wise5/components/embedded/embeddedController.ts
  src/assets/wise5/components/graph/graphController.ts
  src/assets/wise5/components/label/label-authoring/label-authoring.component.ts
  src/assets/wise5/components/match/matchController.ts
  src/assets/wise5/components/table/table-authoring/table-authoring.component.ts
Labels: 1 point

#45 Show scrollbar in NotebookNotes if notes content overflows visible area
  src/app/notebook/notebook-notes/notebook-notes.component.scss
Labels: 1 point

#46 Convert HTML student component to Angular
  src/assets/wise5/authoringTool/components/preview-component/previewComponent.ts
  src/assets/wise5/components/component-student.component.ts
  src/assets/wise5/components/html/html-student/html-student.component.html
  src/assets/wise5/components/html/html-student/html-student.component.ts
  src/assets/wise5/components/html/htmlComponentModule.ts
  src/assets/wise5/components/html/htmlController.ts
  src/assets/wise5/components/html/index.html
  src/assets/wise5/directives/component/component.ts
Labels: 1 point

#41 Add structure choose location now properly displays number and title
  src/assets/wise5/authoringTool/structure/chooseStructureLocation.html
  src/assets/wise5/authoringTool/structure/chooseStructureLocationController.ts
Labels: 1 point

#49 Authored HTML component content does not render with styling
  src/assets/wise5/components/html/html-student/html-student.component.ts
Labels: 1 point

#51 Changed add step into a wizard
  src/app/teacher-hybrid-angular.module.ts
  src/assets/wise5/authoringTool/addNode/addNodeModule.ts
  src/assets/wise5/authoringTool/addNode/choose-new-node-location/choose-new-node-location.component.html
  src/assets/wise5/authoringTool/addNode/choose-new-node-location/choose-new-node-location.component.ts
  src/assets/wise5/authoringTool/addNode/choose-new-node/choose-new-node.component.html
  src/assets/wise5/authoringTool/addNode/choose-new-node/choose-new-node.component.ts
  src/assets/wise5/authoringTool/project/projectAuthoring.html
  src/assets/wise5/authoringTool/project/projectAuthoringComponent.ts
  src/assets/wise5/teacher/teacher-angular-js-module.ts
Labels: 1 point

#53 Fixed issue adding embedded component
  src/assets/wise5/services/teacherProjectService.ts
Labels: 1 point

#56 Fixed typo preventing (un)locking lessons to work in the CM
  src/assets/wise5/classroomMonitor/classroomMonitorComponents/nodeProgress/navItem/navItem.ts
Labels: 1 point

#65 Fixed i18n extraction
  package.json
  src/app/student-hybrid-angular.module.ts
  src/messages.xlf
Labels: 2 points

#63 Change NodeController to use an observable to request component states from MultipleChoice
  src/app/common-hybrid-angular.module.ts
  src/assets/wise5/components/ComponentStateRequest.ts
  src/assets/wise5/components/ComponentStateWrapper.ts
  src/assets/wise5/components/componentService.ts
  src/assets/wise5/components/multipleChoice/multipleChoiceController.ts
  src/assets/wise5/vle/node/nodeController.ts
Labels: 1 point

#70 Convert Multiple Choice student component to Angular
  src/app/student-hybrid-angular.module.ts
  src/assets/wise5/authoringTool/components/preview-component/previewComponent.ts
  src/assets/wise5/components/component-student.component.ts
  src/assets/wise5/components/graph/index.html
  src/assets/wise5/components/html/html-student/html-student.component.ts
  src/assets/wise5/components/multipleChoice/index.html
  src/assets/wise5/components/multipleChoice/multiple-choice-authoring/multiple-choice-authoring.component.html
  src/assets/wise5/components/multipleChoice/multiple-choice-authoring/multiple-choice-authoring.component.scss
  src/assets/wise5/components/multipleChoice/multiple-choice-authoring/multiple-choice-authoring.component.ts
  src/assets/wise5/components/multipleChoice/multiple-choice-grading/multiple-choice-grading.component.ts
  src/assets/wise5/components/multipleChoice/multiple-choice-student/multiple-choice-student.component.html
  src/assets/wise5/components/multipleChoice/multiple-choice-student/multiple-choice-student.component.scss
  src/assets/wise5/components/multipleChoice/multiple-choice-student/multiple-choice-student.component.ts
  src/assets/wise5/components/multipleChoice/multipleChoiceComponentModule.ts
  src/assets/wise5/components/multipleChoice/multipleChoiceController.ts
  src/assets/wise5/directives/component/component.ts
  src/assets/wise5/vle/node/nodeController.ts
Labels: 1 point

#68 In-code/template extraction working with ivy
  .babelrc
  gulpfile.js
  merge-messages.sh
  package-lock.json
  package.json
  pre-commit
  src/messages-code.xlf
  src/messages.xlf
Labels: 1 point

#72 Export notebook items throws an error and does not generate an export
  src/assets/wise5/services/teacherDataService.ts
Labels: 1 point

#77 Make notifyConnectedParts use an observable for Multiple Choice
  src/assets/wise5/components/component-student.component.ts
  src/assets/wise5/components/componentService.ts
  src/assets/wise5/components/multipleChoice/edit-multiple-choice-advanced/edit-multiple-choice-advanced.component.ts
  src/assets/wise5/components/multipleChoice/multiple-choice-student/multiple-choice-student.component.html
  src/assets/wise5/components/multipleChoice/multiple-choice-student/multiple-choice-student.component.ts
  src/assets/wise5/vle/node/nodeController.ts
Labels: 1 point

#64 Add step: automated assessment option and optional initial components
  src/app/authoring-tool/add-component/choose-new-component/choose-new-component.component.ts
  src/app/authoring-tool/import-step/choose-import-step-location/choose-import-step-location.component.ts
  src/app/teacher-hybrid-angular.module.ts
  src/assets/wise5/authoringTool/addNode/NewNodeTemplate.ts
  src/assets/wise5/authoringTool/addNode/add-your-own-node/add-your-own-node.component.html
  src/assets/wise5/authoringTool/addNode/add-your-own-node/add-your-own-node.component.scss
  src/assets/wise5/authoringTool/addNode/add-your-own-node/add-your-own-node.component.ts
  src/assets/wise5/authoringTool/addNode/addNodeModule.ts
  src/assets/wise5/authoringTool/addNode/automatedAssessment/automatedAssessmentChooseItemController.ts
  src/assets/wise5/authoringTool/addNode/automatedAssessment/automatedAssessmentConfigureController.ts
  src/assets/wise5/authoringTool/addNode/automatedAssessment/choose-item.html
  src/assets/wise5/authoringTool/addNode/automatedAssessment/configure-item.html
  src/assets/wise5/authoringTool/addNode/choose-new-node-location/choose-new-node-location.component.html
  src/assets/wise5/authoringTool/addNode/choose-new-node-location/choose-new-node-location.component.ts
  src/assets/wise5/authoringTool/addNode/choose-new-node-template/choose-new-node-template.component.html
  src/assets/wise5/authoringTool/addNode/choose-new-node-template/choose-new-node-template.component.scss
  src/assets/wise5/authoringTool/addNode/choose-new-node-template/choose-new-node-template.component.ts
  src/assets/wise5/authoringTool/addNode/choose-new-node/choose-new-node.component.html
  src/assets/wise5/authoringTool/addNode/choose-new-node/choose-new-node.component.ts
  src/assets/wise5/authoringTool/project/projectAuthoringComponent.ts
  src/assets/wise5/authoringTool/structure/chooseStructureController.ts
  src/assets/wise5/authoringTool/structure/structureAuthoringModule.ts
  src/assets/wise5/components/html/i18n/i18n_en.json
  src/messages.xlf
Labels: 2 points

#82 New option to exclude component score from total score
  karma.conf.js
  src/app/authoring-tool/edit-component-exclude-from-total-score/edit-component-exclude-from-total-score.component.html
  src/app/authoring-tool/edit-component-exclude-from-total-score/edit-component-exclude-from-total-score.component.ts
  src/app/services/annotationService.spec.ts
  src/app/services/projectService.spec.ts
  src/app/services/sampleData/curriculum/Demo.project.json
  src/app/services/teacherProjectService.spec.ts
  src/app/teacher-hybrid-angular.module.ts
  src/assets/wise5/classroomMonitor/classroomMonitorComponents/nodeGrading/nodeGradingView/nodeGradingView.ts
  src/assets/wise5/classroomMonitor/classroomMonitorComponents/nodeProgress/navItem/navItem.ts
  src/assets/wise5/classroomMonitor/studentGrading/studentGradingController.ts
  src/assets/wise5/components/animation/edit-animation-advanced/edit-animation-advanced.component.html
  src/assets/wise5/components/audioOscillator/edit-audio-oscillator-advanced/edit-audio-oscillator-advanced.component.html
  src/assets/wise5/components/conceptMap/edit-concept-map-advanced/edit-concept-map-advanced.component.html
  src/assets/wise5/components/discussion/edit-discussion-advanced/edit-discussion-advanced.component.html
  src/assets/wise5/components/draw/edit-draw-advanced/edit-draw-advanced.component.html
  src/assets/wise5/components/embedded/edit-embedded-advanced/edit-embedded-advanced.component.html
  src/assets/wise5/components/graph/edit-graph-advanced/edit-graph-advanced.component.html
  src/assets/wise5/components/label/edit-label-advanced/edit-label-advanced.component.html
  src/assets/wise5/components/match/edit-match-advanced/edit-match-advanced.component.html
  src/assets/wise5/components/multipleChoice/edit-multiple-choice-advanced/edit-multiple-choice-advanced.component.html
  src/assets/wise5/components/openResponse/edit-open-response-advanced/edit-open-response-advanced.component.html
  src/assets/wise5/components/summary/edit-summary-advanced/edit-summary-advanced.component.html
  src/assets/wise5/components/table/edit-table-advanced/edit-table-advanced.component.html
  src/assets/wise5/services/annotationService.ts
  src/assets/wise5/services/projectService.ts
  src/assets/wise5/services/studentDataService.ts
  src/assets/wise5/services/studentStatusService.ts
  src/assets/wise5/services/teacherDataService.ts
  src/assets/wise5/teacher/teacher-angular-js-module.ts
Labels: 1 point

#81 Make wiselink work again
  src/assets/wise5/components/html/html-student/html-student.component.html
  src/assets/wise5/components/html/html-student/html-student.component.ts
  src/assets/wise5/directives/components.ts
  src/assets/wise5/directives/wiselink/wiselink.html
  src/assets/wise5/directives/wiselink/wiselink.js
  src/assets/wise5/services/nodeService.ts
  src/assets/wise5/services/utilService.ts
Labels: 1 point

#84 Disable Open Response textarea when all submits are used up
  src/assets/wise5/authoringTool/i18n/i18n_en.json
  src/assets/wise5/components/componentController.ts
  src/assets/wise5/components/openResponse/edit-open-response-advanced/edit-open-response-advanced.component.html
  src/assets/wise5/components/openResponse/openResponseController.ts
Labels: 1 point

#86 Prevent copy pasting images into TinyMCE editor
  src/assets/wise5/directives/wise-tinymce-editor/wise-tinymce-editor.component.ts
Labels: 1 point

#89 Created common parent class for editing advanced component field
  src/app/authoring-tool/edit-component-exclude-from-total-score/edit-component-exclude-from-total-score.component.html
  src/app/authoring-tool/edit-component-exclude-from-total-score/edit-component-exclude-from-total-score.component.ts
  src/app/authoring-tool/edit-component-field.component.ts
  src/app/authoring-tool/edit-component-max-score/edit-component-max-score.component.html
  src/app/authoring-tool/edit-component-max-score/edit-component-max-score.component.ts
  src/app/authoring-tool/edit-component-width/edit-component-width.component.html
  src/app/authoring-tool/edit-component-width/edit-component-width.component.ts
Labels: 1 point

#90 Make attachStudentAssets use an observable for Discussion
  src/assets/wise5/components/discussion/discussionController.ts
  src/assets/wise5/services/studentAssetService.ts
  src/assets/wise5/themes/default/templates/studentAssetDialog.html
  src/assets/wise5/themes/default/themeController.js
  src/assets/wise5/vle/node/nodeController.ts
  src/assets/wise5/vle/studentAsset/StudentAssetRequest.ts
  src/assets/wise5/vle/studentAsset/studentAsset.ts
  src/assets/wise5/vle/studentAsset/studentAssetController.ts
Labels: 1 point

#95 Make wiselinks work with component annotations
  src/app/common-hybrid-angular.module.ts
  src/app/services/wiseLinkService.ts
  src/assets/wise5/components/animation/index.html
  src/assets/wise5/components/audioOscillator/index.html
  src/assets/wise5/components/conceptMap/index.html
  src/assets/wise5/components/discussion/index.html
  src/assets/wise5/components/draw/index.html
  src/assets/wise5/components/embedded/index.html
  src/assets/wise5/components/graph/index.html
  src/assets/wise5/components/html/html-student/html-student.component.html
  src/assets/wise5/components/html/html-student/html-student.component.ts
  src/assets/wise5/components/label/index.html
  src/assets/wise5/components/match/index.html
  src/assets/wise5/components/multipleChoice/multiple-choice-student/multiple-choice-student.component.html
  src/assets/wise5/components/openResponse/index.html
  src/assets/wise5/components/table/index.html
  src/assets/wise5/directives/componentAnnotations/component-annotations.component.html
  src/assets/wise5/directives/componentAnnotations/component-annotations.component.ts
  src/assets/wise5/services/utilService.ts
Labels: 1 point

#100 Convert Outside URL student component to Angular
  src/app/student-hybrid-angular.module.ts
  src/assets/wise5/authoringTool/components/preview-component/previewComponent.ts
  src/assets/wise5/components/outsideURL/index.html
  src/assets/wise5/components/outsideURL/outside-url-student/outside-url-student.component.html
  src/assets/wise5/components/outsideURL/outside-url-student/outside-url-student.component.ts
  src/assets/wise5/components/outsideURL/outsideURLComponentModule.ts
  src/assets/wise5/components/outsideURL/outsideURLController.ts
  src/assets/wise5/directives/component/component.ts
Labels: 1 point

#98 Created Node class
  src/app/services/projectService.spec.ts
  src/assets/wise5/classroomMonitor/classroomMonitorComponents/nodeProgress/navItem/navItem.ts
  src/assets/wise5/classroomMonitor/classroomMonitorComponents/shared/nodeIcon/node-icon.component.ts
  src/assets/wise5/classroomMonitor/classroomMonitorComponents/shared/nodeInfo/nodeInfo.ts
  src/assets/wise5/common/Node.spec.ts
  src/assets/wise5/common/Node.ts
  src/assets/wise5/services/projectService.ts
  src/assets/wise5/services/studentDataService.ts
Labels: 1 point

#93 Builds in other languages
  angular.json
  gulpfile.js
  package.json
  scripts/beforeInstall.sh
  src/app/student/student.service.ts
  src/locale/messages.es.xlf
  src/locale/messages.ja.xlf
  src/locale/messages.pt.xlf
  src/locale/messages.tr.xlf
  src/locale/messages.zh-Hans.xlf
  src/locale/messages.zh-Hant.xlf
  src/messages.xlf
Labels: 4 points

#105 TinyMCE UI changes
  src/assets/tinymce/wise/content.css
  src/assets/tinymce/wise/content.inline.css
  src/assets/tinymce/wise/content.inline.min.css
  src/assets/tinymce/wise/content.inline.min.css.map
  src/assets/tinymce/wise/content.min.css
  src/assets/tinymce/wise/content.min.css.map
  src/assets/tinymce/wise/content.mobile.css
  src/assets/tinymce/wise/content.mobile.min.css
  src/assets/tinymce/wise/content.mobile.min.css.map
  src/assets/tinymce/wise/fonts/tinymce-mobile.woff
  src/assets/tinymce/wise/skin.css
  src/assets/tinymce/wise/skin.min.css
  src/assets/tinymce/wise/skin.min.css.map
  src/assets/tinymce/wise/skin.mobile.css
  src/assets/tinymce/wise/skin.mobile.min.css
  src/assets/tinymce/wise/skin.mobile.min.css.map
  src/assets/tinymce/wise/skin.shadowdom.css
  src/assets/tinymce/wise/skin.shadowdom.min.css
  src/assets/tinymce/wise/skin.shadowdom.min.css.map
  src/assets/wise5/directives/wise-tinymce-editor/wise-authoring-tinymce-editor.component.ts
  src/assets/wise5/directives/wise-tinymce-editor/wise-tinymce-editor.component.ts
  src/messages.xlf
Labels: 1 point

#108 Teacher score and comment does not override automated score and comment
  src/assets/wise5/services/annotationService.ts
Labels: 1 point

#103 Use Node in NodeAuthoringController.
  src/assets/wise5/authoringTool/asset/projectAssetAuthoringComponent.ts
  src/assets/wise5/authoringTool/authoringToolComponent.ts
  src/assets/wise5/authoringTool/importComponent/choose-component-location.component.ts
  src/assets/wise5/authoringTool/importComponent/choose-component.component.ts
  src/assets/wise5/authoringTool/info/projectInfoAuthoringComponent.ts
  src/assets/wise5/authoringTool/main/mainAuthoringComponent.ts
  src/assets/wise5/authoringTool/milestones/milestonesAuthoringComponent.ts
  src/assets/wise5/authoringTool/node/advanced/branch/node-advanced-branch-authoring.component.ts
  src/assets/wise5/authoringTool/node/advanced/constraint/node-advanced-constraint-authoring.component.ts
  src/assets/wise5/authoringTool/node/advanced/node-advanced-authoring.component.html
  src/assets/wise5/authoringTool/node/advanced/node-advanced-authoring.component.ts
  src/assets/wise5/authoringTool/node/advanced/path/node-advanced-path-authoring.component.ts
  src/assets/wise5/authoringTool/node/editRubric/edit-rubric.component.ts
  src/assets/wise5/authoringTool/node/nodeAuthoring.html
  src/assets/wise5/authoringTool/node/nodeAuthoringComponent.ts
  src/assets/wise5/authoringTool/notebook/notebookAuthoringComponent.ts
  src/assets/wise5/authoringTool/project/projectAuthoringComponent.ts
  src/assets/wise5/classroomMonitor/classroomMonitorComponents/nodeProgress/nodeProgressView/nodeProgressView.ts
  src/assets/wise5/common/Node.ts
  src/assets/wise5/teacher/teacher-angular-js-module.ts
Labels: 1 point
