Repository WISE-Community/WISE-Client, pull requests merged in 2021-06, with the labels that each got.

#170 Exclude workgroups no longer in run from student statuses
  src/assets/wise5/services/studentStatusService.ts
  src/messages.xlf
Labels: 1 point

#172 Separated authoring-tool-module into project/node/component-authoring-module
  src/assets/wise5/authoringTool/authoring-tool.module.ts
  src/assets/wise5/authoringTool/node/node-authoring.module.ts
  src/assets/wise5/authoringTool/project/project-authoring.module.ts
  src/assets/wise5/components/component-authoring.module.ts
Labels: 1 point

#167 Select step icon from AT node view
  src/app/about/about.component.html
  src/app/common-hybrid-angular.module.ts
  src/app/teacher-hybrid-angular.module.ts
  src/assets/img/icons/ki-color-add.svg
  src/assets/img/icons/ki-color-connect.svg
  src/assets/img/icons/ki-color-cycle copy.svg
  src/assets/img/icons/ki-color-cycle.svg
  src/assets/img/icons/ki-color-distinguish.svg
  src/assets/img/icons/ki-color-elicit.svg
  src/assets/wise5/authoringTool/node/nodeAuthoring.html
  src/assets/wise5/classroomMonitor/classroomMonitorComponents/shared/nodeIcon/node-icon.component.html
  src/assets/wise5/classroomMonitor/classroomMonitorComponents/shared/nodeIcon/node-icon.component.scss
  src/assets/wise5/classroomMonitor/classroomMonitorComponents/shared/nodeIcon/node-icon.component.ts
  src/assets/wise5/common/Node.spec.ts
  src/assets/wise5/common/Node.ts
  src/assets/wise5/common/node-icon-chooser-dialog/node-icon-chooser-dialog.component.html
  src/assets/wise5/common/node-icon-chooser-dialog/node-icon-chooser-dialog.component.scss
  src/assets/wise5/common/node-icon-chooser-dialog/node-icon-chooser-dialog.component.spec.ts
  src/assets/wise5/common/node-icon-chooser-dialog/node-icon-chooser-dialog.component.ts
  src/assets/wise5/common/stepTools/step-tools.component.ts
  src/messages.xlf
Labels: 4 points, 8 points

#178 Only show steps with work in Teacher Tools node select dropdown
  src/assets/wise5/authoringTool/components/shared/toolbar/toolbar.ts
  src/assets/wise5/classroomMonitor/classroomMonitorComponents/shared/toolbar/toolbar.ts
  src/assets/wise5/common/stepTools/step-tools.component.ts
  src/assets/wise5/services/studentStatusService.ts
Labels: 1 point

#185 Extracted prompt authoring
  src/app/authoring-tool/edit-component-prompt/edit-component-prompt.component.html
  src/app/authoring-tool/edit-component-prompt/edit-component-prompt.component.ts
  src/app/teacher-hybrid-angular.module.ts
  src/assets/wise5/components/animation/animation-authoring/animation-authoring.component.html
  src/assets/wise5/components/animation/animation-authoring/animation-authoring.component.scss
  src/assets/wise5/components/audioOscillator/audio-oscillator-authoring/audio-oscillator-authoring.component.html
  src/assets/wise5/components/audioOscillator/audio-oscillator-authoring/audio-oscillator-authoring.component.scss
  src/assets/wise5/components/component-authoring.module.ts
  src/assets/wise5/components/conceptMap/concept-map-authoring/concept-map-authoring.component.html
  src/assets/wise5/components/conceptMap/concept-map-authoring/concept-map-authoring.component.scss
  src/assets/wise5/components/discussion/discussion-authoring/discussion-authoring.component.html
  src/assets/wise5/components/discussion/discussion-authoring/discussion-authoring.component.scss
  src/assets/wise5/components/draw/draw-authoring/draw-authoring.component.html
  src/assets/wise5/components/draw/draw-authoring/draw-authoring.component.scss
  src/assets/wise5/components/graph/graph-authoring/graph-authoring.component.html
  src/assets/wise5/components/graph/graph-authoring/graph-authoring.component.scss
  src/assets/wise5/components/label/label-authoring/label-authoring.component.html
  src/assets/wise5/components/label/label-authoring/label-authoring.component.scss
  src/assets/wise5/components/match/match-authoring/match-authoring.component.html
  src/assets/wise5/components/match/match-authoring/match-authoring.component.scss
  src/assets/wise5/components/multipleChoice/multiple-choice-authoring/multiple-choice-authoring.component.html
  src/assets/wise5/components/multipleChoice/multiple-choice-authoring/multiple-choice-authoring.component.scss
  src/assets/wise5/components/openResponse/open-response-authoring/open-response-authoring.component.html
  src/assets/wise5/components/summary/summary-authoring/summary-authoring.component.html
  src/assets/wise5/components/summary/summary-authoring/summary-authoring.component.scss
  src/assets/wise5/components/table/table-authoring/table-authoring.component.html
  src/assets/wise5/components/table/table-authoring/table-authoring.component.scss
  src/messages.xlf
Labels: 1 point

#181 Extracted notebook module
  src/app/common-hybrid-angular.module.ts
  src/app/notebook/notebook-parent/notebook-parent.component.ts
  src/app/notebook/notebook.module.ts
  src/assets/wise5/classroomMonitor/classroom-monitor.module.ts
  src/assets/wise5/classroomMonitor/classroomMonitorComponents/notebook/notebook.ts
Labels: 1 point

#183 Changed retrieveStudentStatuses() to use subscribe().
  src/app/services/studentStatusService.spec.ts
  src/assets/wise5/services/studentStatusService.ts
Labels: 1 point

#193 Replace all nodeId and componentId references when importing a step
  src/app/services/teacherProjectService.spec.ts
  src/assets/wise5/authoringTool/structure/chooseStructureLocationController.ts
  src/assets/wise5/services/teacherProjectService.ts
Labels: 1 point

#174 Convert Match student component to Angular
  package-lock.json
  package.json
  src/app/authoring-tool/edit-advanced-component/editAdvancedComponentAngularJSController.ts
  src/app/common-hybrid-angular.module.ts
  src/app/student-hybrid-angular.module.ts
  src/app/student/student.component.module.ts
  src/assets/wise5/authoringTool/components/component-authoring.component.ts
  src/assets/wise5/authoringTool/components/preview-component/previewComponent.ts
  src/assets/wise5/common-angular-js-module.ts
  src/assets/wise5/components/audioOscillator/audio-oscillator-student/audio-oscillator-student.component.html
  src/assets/wise5/components/audioOscillator/audio-oscillator-student/audio-oscillator-student.component.scss
  src/assets/wise5/components/component-student.component.ts
  src/assets/wise5/components/draw/draw-student/draw-student.component.html
  src/assets/wise5/components/draw/draw-student/draw-student.component.scss
  src/assets/wise5/components/label/label-student/label-student.component.html
  src/assets/wise5/components/label/label-student/label-student.component.scss
  src/assets/wise5/components/match/edit-match-advanced/edit-match-advanced.component.ts
  src/assets/wise5/components/match/i18n/i18n_en.json
  src/assets/wise5/components/match/index.html
  src/assets/wise5/components/match/match-authoring/match-authoring.component.scss
  src/assets/wise5/components/match/match-student/add-choice-button/add-choice-button.component.html
  src/assets/wise5/components/match/match-student/add-choice-button/add-choice-button.component.ts
  src/assets/wise5/components/match/match-student/add-match-choice-dialog/add-match-choice-dialog.html
  src/assets/wise5/components/match/match-student/add-match-choice-dialog/add-match-choice-dialog.ts
  src/assets/wise5/components/match/match-student/delete-choice-button/delete-choice-button.component.html
  src/assets/wise5/components/match/match-student/delete-choice-button/delete-choice-button.component.scss
  src/assets/wise5/components/match/match-student/delete-choice-button/delete-choice-button.component.spec.ts
  src/assets/wise5/components/match/match-student/delete-choice-button/delete-choice-button.component.ts
  src/assets/wise5/components/match/match-student/match-choice-item/match-choice-item.component.html
  src/assets/wise5/components/match/match-student/match-choice-item/match-choice-item.component.scss
  src/assets/wise5/components/match/match-student/match-choice-item/match-choice-item.component.ts
  src/assets/wise5/components/match/match-student/match-feedback-section/match-feedback-section.component.html
  src/assets/wise5/components/match/match-student/match-feedback-section/match-feedback-section.component.ts
  src/assets/wise5/components/match/match-student/match-status-icon/match-status-icon.component.html
  src/assets/wise5/components/match/match-student/match-status-icon/match-status-icon.component.ts
  src/assets/wise5/components/match/match-student/match-student.component.html
  src/assets/wise5/components/match/match-student/match-student.component.scss
  src/assets/wise5/components/match/match-student/match-student.component.spec.ts
  src/assets/wise5/components/match/match-student/match-student.component.ts
  src/assets/wise5/components/match/match-student/match-student.module.ts
  src/assets/wise5/components/match/matchComponentModule.ts
  src/assets/wise5/components/match/matchController.ts
  src/assets/wise5/components/multipleChoice/multiple-choice-authoring/multiple-choice-authoring.component.ts
  src/assets/wise5/components/multipleChoice/multiple-choice-student/multiple-choice-student.component.html
  src/assets/wise5/components/multipleChoice/multiple-choice-student/multiple-choice-student.component.scss
  src/assets/wise5/components/multipleChoice/multiple-choice-student/multiple-choice-student.component.ts
  src/assets/wise5/directives/component-save-submit-buttons/component-save-submit-buttons.component.ts
  src/assets/wise5/directives/component/component.ts
  src/assets/wise5/vle/node/nodeController.ts
  src/messages.xlf
Labels: 32 points

#196 Extracted and upgraded maxScore grading to Angular
  src/app/teacher-hybrid-angular.module.ts
  src/assets/wise5/classroomMonitor/classroomMonitorComponents/grading-edit-component-max-score/grading-edit-component-max-score.component.html
  src/assets/wise5/classroomMonitor/classroomMonitorComponents/grading-edit-component-max-score/grading-edit-component-max-score.component.spec.ts
  src/assets/wise5/classroomMonitor/classroomMonitorComponents/grading-edit-component-max-score/grading-edit-component-max-score.component.ts
  src/assets/wise5/classroomMonitor/classroomMonitorComponents/shared/componentGrading/componentGrading.html
  src/assets/wise5/classroomMonitor/classroomMonitorComponents/shared/componentGrading/componentGrading.ts
  src/assets/wise5/classroomMonitor/classroomMonitorComponents/shared/workgroupComponentGrading/workgroupComponentGrading.html
  src/assets/wise5/classroomMonitor/classroomMonitorComponents/shared/workgroupComponentRevisions/workgroupComponentRevisions.ts
  src/assets/wise5/components/component-grading.module.ts
  src/assets/wise5/services/teacherProjectService.ts
Labels: 1 point

#200 Extracted CopyNodesService
  src/app/authoring-tool/import-step/choose-import-step-location/choose-import-step-location.component.ts
  src/app/services/dataExportService.spec.ts
  src/app/services/milestoneService.spec.ts
  src/app/services/spaceService.spec.ts
  src/app/services/teacherProjectService.spec.ts
  src/app/teacher-hybrid-angular.module.ts
  src/assets/wise5/directives/wise-tinymce-editor/wise-authoring-tinymce-editor.component.spec.ts
  src/assets/wise5/services/copyNodesService.ts
  src/assets/wise5/services/insertNodesService.ts
  src/assets/wise5/services/teacherProjectService.ts
Labels: 1 point

#206 Student data that contains an html image element includes additional attributes that shouldn't be saved
  src/assets/wise5/components/match/match-student/match-student.component.spec.ts
  src/assets/wise5/components/match/match-student/match-student.component.ts
  src/assets/wise5/components/multipleChoice/multiple-choice-student/multiple-choice-student.component.spec.ts
  src/assets/wise5/components/multipleChoice/multiple-choice-student/multiple-choice-student.component.ts
Labels: 1 point

#187 Convert Concept Map student component to Angular
  src/app/services/conceptMapService.spec.ts
  src/app/student-hybrid-angular.module.ts
  src/assets/wise5/authoringTool/components/preview-component/previewComponent.ts
  src/assets/wise5/components/component-student.component.ts
  src/assets/wise5/components/conceptMap/concept-map-authoring/concept-map-authoring.component.html
  src/assets/wise5/components/conceptMap/concept-map-authoring/concept-map-authoring.component.scss
  src/assets/wise5/components/conceptMap/concept-map-student/concept-map-student.component.html
  src/assets/wise5/components/conceptMap/concept-map-student/concept-map-student.component.scss
  src/assets/wise5/components/conceptMap/concept-map-student/concept-map-student.component.spec.ts
  src/assets/wise5/components/conceptMap/concept-map-student/concept-map-student.component.ts
  src/assets/wise5/components/conceptMap/conceptMapComponentModule.ts
  src/assets/wise5/components/conceptMap/conceptMapController.ts
  src/assets/wise5/components/conceptMap/conceptMapNode.ts
  src/assets/wise5/components/conceptMap/conceptMapService.ts
  src/assets/wise5/components/conceptMap/edit-concept-map-advanced/edit-concept-map-advanced.component.ts
  src/assets/wise5/components/conceptMap/index.html
  src/assets/wise5/directives/component/component.ts
  src/assets/wise5/directives/html-dialog/html-dialog.html
  src/assets/wise5/directives/html-dialog/html-dialog.ts
  src/assets/wise5/vle/node/nodeController.ts
  src/assets/wise5/vle/studentAsset/studentAssetController.ts
  src/messages.xlf
Labels: 1 point

#194 Authoring Tool can't click Home button and then go back to step previously opened
  src/assets/wise5/authoringTool/node/nodeAuthoringComponent.ts
  src/assets/wise5/common/stepTools/step-tools.component.ts
Labels: 1 point

#209 Updated Node from v10 to v14 for Docker dev
  Dockerfile
Labels: 1 point

#212 Extracted EditComponentScore and upgraded to Angular
  src/app/teacher-hybrid-angular.module.ts
  src/assets/wise5/classroomMonitor/classroomMonitorComponents/edit-component-score/edit-component-score.component.html
  src/assets/wise5/classroomMonitor/classroomMonitorComponents/edit-component-score/edit-component-score.component.spec.ts
  src/assets/wise5/classroomMonitor/classroomMonitorComponents/edit-component-score/edit-component-score.component.ts
  src/assets/wise5/classroomMonitor/classroomMonitorComponents/grading-edit-component-max-score/grading-edit-component-max-score.component.ts
  src/assets/wise5/classroomMonitor/classroomMonitorComponents/shared/componentGrading/componentGrading.html
  src/assets/wise5/classroomMonitor/classroomMonitorComponents/shared/componentGrading/componentGrading.ts
  src/assets/wise5/components/component-grading.module.ts
  src/messages.xlf
Labels: 1 point

#214 Default feedback annotation
  src/app/authoring-tool/edit-advanced-component/edit-component-default-feedback/edit-component-default-feedback.component.html
  src/app/authoring-tool/edit-advanced-component/edit-component-default-feedback/edit-component-default-feedback.component.scss
  src/app/authoring-tool/edit-advanced-component/edit-component-default-feedback/edit-component-default-feedback.component.spec.ts
  src/app/authoring-tool/edit-advanced-component/edit-component-default-feedback/edit-component-default-feedback.component.ts
  src/app/teacher-hybrid-angular.module.ts
  src/assets/wise5/components/animation/animationController.ts
  src/assets/wise5/components/animation/edit-animation-advanced/edit-animation-advanced.component.html
  src/assets/wise5/components/audioOscillator/audio-oscillator-student/audio-oscillator-student.component.ts
  src/assets/wise5/components/audioOscillator/edit-audio-oscillator-advanced/edit-audio-oscillator-advanced.component.html
  src/assets/wise5/components/component-authoring.module.ts
  src/assets/wise5/components/component-student.component.ts
  src/assets/wise5/components/componentController.ts
  src/assets/wise5/components/conceptMap/concept-map-student/concept-map-student.component.ts
  src/assets/wise5/components/conceptMap/edit-concept-map-advanced/edit-concept-map-advanced.component.html
  src/assets/wise5/components/draw/draw-student/draw-student.component.ts
  src/assets/wise5/components/draw/edit-draw-advanced/edit-draw-advanced.component.html
  src/assets/wise5/components/embedded/edit-embedded-advanced/edit-embedded-advanced.component.html
  src/assets/wise5/components/embedded/embeddedController.ts
  src/assets/wise5/components/graph/edit-graph-advanced/edit-graph-advanced.component.html
  src/assets/wise5/components/graph/graphController.ts
  src/assets/wise5/components/label/edit-label-advanced/edit-label-advanced.component.html
  src/assets/wise5/components/label/label-student/label-student.component.ts
  src/assets/wise5/components/match/edit-match-advanced/edit-match-advanced.component.html
  src/assets/wise5/components/match/match-student/match-student.component.ts
  src/assets/wise5/components/multipleChoice/edit-multiple-choice-advanced/edit-multiple-choice-advanced.component.html
  src/assets/wise5/components/multipleChoice/multiple-choice-student/multiple-choice-student.component.ts
  src/assets/wise5/components/openResponse/edit-open-response-advanced/edit-open-response-advanced.component.html
  src/assets/wise5/components/openResponse/openResponseController.ts
  src/assets/wise5/components/table/edit-table-advanced/edit-table-advanced.component.html
  src/assets/wise5/components/table/tableController.ts
  src/assets/wise5/directives/componentAnnotations/component-annotations.component.ts
  src/assets/wise5/services/studentDataService.ts
  src/messages.xlf
Labels: 1 point

#215 Extracted and upgraded edit component comment to Angular
  src/app/teacher-hybrid-angular.module.ts
  src/assets/wise5/classroomMonitor/classroomMonitorComponents/edit-component-comment/edit-component-comment.component.html
  src/assets/wise5/classroomMonitor/classroomMonitorComponents/edit-component-comment/edit-component-comment.component.spec.ts
  src/assets/wise5/classroomMonitor/classroomMonitorComponents/edit-component-comment/edit-component-comment.component.ts
  src/assets/wise5/classroomMonitor/classroomMonitorComponents/shared/componentGrading/componentGrading.html
  src/assets/wise5/classroomMonitor/classroomMonitorComponents/shared/componentGrading/componentGrading.ts
  src/assets/wise5/components/component-grading.module.ts
  src/messages.xlf
Labels: 1 point

#216 Replaced Dragula with Material Drag and Drop
  package-lock.json
  package.json
  src/app/common-hybrid-angular.module.ts
  src/app/teacher-hybrid-angular.module.ts
  src/assets/wise5/components/component-student.component.ts
  src/assets/wise5/components/match/match-student/match-student.component.html
  src/assets/wise5/components/match/match-student/match-student.component.scss
  src/assets/wise5/components/match/match-student/match-student.component.spec.ts
  src/assets/wise5/components/match/match-student/match-student.component.ts
  src/assets/wise5/components/match/match-student/match-student.module.ts
  src/assets/wise5/themes/default/style/monitor.css
  src/assets/wise5/themes/default/style/monitor.css.map
  src/assets/wise5/themes/default/style/monitor.scss
  src/assets/wise5/themes/default/style/vle.css
  src/assets/wise5/themes/default/style/vle.css.map
  src/assets/wise5/themes/default/style/vle.scss
  src/messages.xlf
Labels: 1 point

#217 Convert Embedded student component to Angular
  src/app/student-hybrid-angular.module.ts
  src/assets/wise5/authoringTool/components/preview-component/previewComponent.ts
  src/assets/wise5/components/component-student.component.ts
  src/assets/wise5/components/embedded/embedded-student/embedded-student.component.html
  src/assets/wise5/components/embedded/embedded-student/embedded-student.component.scss
  src/assets/wise5/components/embedded/embedded-student/embedded-student.component.spec.ts
  src/assets/wise5/components/embedded/embedded-student/embedded-student.component.ts
  src/assets/wise5/components/embedded/embeddedComponentModule.ts
  src/assets/wise5/components/embedded/embeddedController.ts
  src/assets/wise5/components/embedded/index.html
  src/assets/wise5/directives/component/component.ts
  src/assets/wise5/vle/node/nodeController.ts
Labels: 1 point

#223 Upgraded ComponentGrading to Angular
  src/app/teacher-hybrid-angular.module.ts
  src/assets/wise5/classroomMonitor/classroomMonitorComponents/edit-component-annotations/edit-component-annotations.component.html
  src/assets/wise5/classroomMonitor/classroomMonitorComponents/edit-component-annotations/edit-component-annotations.component.ts
  src/assets/wise5/classroomMonitor/classroomMonitorComponents/edit-component-score/edit-component-score.component.html
  src/assets/wise5/classroomMonitor/classroomMonitorComponents/shared/componentGrading/componentGrading.html
  src/assets/wise5/classroomMonitor/classroomMonitorComponents/shared/componentGrading/componentGrading.ts
  src/assets/wise5/classroomMonitor/classroomMonitorComponents/shared/shared.ts
  src/assets/wise5/classroomMonitor/classroomMonitorComponents/shared/workgroupComponentGrading/workgroupComponentGrading.html
  src/assets/wise5/classroomMonitor/classroomMonitorComponents/shared/workgroupComponentRevisions/workgroupComponentRevisions.ts
  src/assets/wise5/components/component-grading.module.ts
  src/messages.xlf
Labels: 1 point

#225 Convert Animation student component to Angular
  src/app/common-hybrid-angular.module.ts
  src/app/student-hybrid-angular.module.ts
  src/assets/wise5/authoringTool/components/preview-component/previewComponent.ts
  src/assets/wise5/components/animation/animation-student/animation-student.component.html
  src/assets/wise5/components/animation/animation-student/animation-student.component.scss
  src/assets/wise5/components/animation/animation-student/animation-student.component.spec.ts
  src/assets/wise5/components/animation/animation-student/animation-student.component.ts
  src/assets/wise5/components/animation/animationComponentModule.ts
  src/assets/wise5/components/animation/animationService.ts
  src/assets/wise5/components/animation/index.html
  src/assets/wise5/components/component-student.component.ts
  src/assets/wise5/directives/component/component.ts
  src/assets/wise5/vle/node/nodeController.ts
  src/messages.xlf
Labels: 1 point

#228 Upgraded ComponentRevisionsInfo to Angular
  src/app/teacher-hybrid-angular.module.ts
  src/assets/wise5/classroomMonitor/classroomMonitorComponents/component-state-info/component-state-info.component.html
  src/assets/wise5/classroomMonitor/classroomMonitorComponents/component-state-info/component-state-info.component.ts
  src/assets/wise5/classroomMonitor/classroomMonitorComponents/shared/componentRevisionsInfo/componentRevisionsInfo.ts
  src/assets/wise5/classroomMonitor/classroomMonitorComponents/shared/shared.ts
  src/assets/wise5/classroomMonitor/classroomMonitorComponents/shared/workgroupComponentGrading/workgroupComponentGrading.html
  src/assets/wise5/classroomMonitor/classroomMonitorComponents/shared/workgroupComponentGrading/workgroupComponentGrading.ts
  src/assets/wise5/classroomMonitor/classroomMonitorComponents/shared/workgroupComponentRevisions/workgroupComponentRevisions.ts
  src/assets/wise5/components/component-grading.module.ts
  src/messages.xlf
Labels: 1 point

#231 Upgraded WorkgroupComponentRevisions to Angular
  src/app/teacher-hybrid-angular.module.ts
  src/assets/wise5/classroomMonitor/classroomMonitorComponents/shared/component-grading.component.ts
  src/assets/wise5/classroomMonitor/classroomMonitorComponents/shared/shared.ts
  src/assets/wise5/classroomMonitor/classroomMonitorComponents/shared/workgroupComponentGrading/workgroupComponentGrading.html
  src/assets/wise5/classroomMonitor/classroomMonitorComponents/shared/workgroupComponentGrading/workgroupComponentGrading.ts
  src/assets/wise5/classroomMonitor/classroomMonitorComponents/shared/workgroupComponentRevisions/workgroupComponentRevisions.ts
  src/assets/wise5/classroomMonitor/classroomMonitorComponents/view-component-revisions/view-component-revisions.component.html
  src/assets/wise5/classroomMonitor/classroomMonitorComponents/view-component-revisions/view-component-revisions.component.scss
  src/assets/wise5/classroomMonitor/classroomMonitorComponents/view-component-revisions/view-component-revisions.component.ts
  src/assets/wise5/components/component-grading.module.ts
  src/assets/wise5/components/table/table-grading/table-grading.component.spec.ts
  src/messages.xlf
Labels: 1 point

#230 Convert Open Response student component to Angular
  src/app/student-hybrid-angular.module.ts
  src/assets/wise5/authoringTool/components/preview-component/previewComponent.ts
  src/assets/wise5/components/component-student.component.ts
  src/assets/wise5/components/conceptMap/concept-map-student/concept-map-student.component.ts
  src/assets/wise5/components/openResponse/index.html
  src/assets/wise5/components/openResponse/open-response-student/open-response-student.component.html
  src/assets/wise5/components/openResponse/open-response-student/open-response-student.component.scss
  src/assets/wise5/components/openResponse/open-response-student/open-response-student.component.spec.ts
  src/assets/wise5/components/openResponse/open-response-student/open-response-student.component.ts
  src/assets/wise5/components/openResponse/openResponseComponentModule.ts
  src/assets/wise5/directives/component/component.ts
  src/assets/wise5/directives/html-dialog/html-dialog.html
  src/assets/wise5/directives/html-dialog/html-dialog.ts
  src/assets/wise5/directives/safeUrl/safe-url.pipe.ts
  src/assets/wise5/vle/node/nodeController.ts
  src/messages.xlf
Labels: 1 point

#234 Timeout CRater requests after 40 seconds
  src/app/services/cRaterService.spec.ts
  src/assets/wise5/components/openResponse/open-response-student/open-response-student.component.spec.ts
  src/assets/wise5/components/openResponse/open-response-student/open-response-student.component.ts
  src/assets/wise5/services/cRaterService.ts
  src/assets/wise5/vle/node/nodeController.ts
  src/messages.xlf
Labels: 1 point
