Repository WISE-Community/WISE-Client, pull requests merged in 2021-12, with the labels that each got.

#413 refactor(Peer Chat): Refactor into smaller components and update UI
  src/app/common-hybrid-angular.module.ts
  src/app/student-hybrid-angular.module.ts
  src/app/teacher/component-grading.module.ts
  src/assets/wise5/components/dialogGuidance/dialog-guidance-student/dialog-guidance-student.component.html
  src/assets/wise5/components/dialogGuidance/dialog-guidance-student/dialog-guidance-student.component.scss
  src/assets/wise5/components/dialogGuidance/dialog-response/dialog-response.component.html
  src/assets/wise5/components/dialogGuidance/dialog-responses/dialog-responses.component.scss
  src/assets/wise5/components/peerChat/edit-peer-chat-advanced-component/edit-peer-chat-advanced-component.component.spec.ts
  src/assets/wise5/components/peerChat/peer-chat-authoring/peer-chat-authoring.component.spec.ts
  src/assets/wise5/components/peerChat/peer-chat-chat-box/peer-chat-chat-box.component.html
  src/assets/wise5/components/peerChat/peer-chat-chat-box/peer-chat-chat-box.component.scss
  src/assets/wise5/components/peerChat/peer-chat-chat-box/peer-chat-chat-box.component.spec.ts
  src/assets/wise5/components/peerChat/peer-chat-chat-box/peer-chat-chat-box.component.ts
  src/assets/wise5/components/peerChat/peer-chat-grading/peer-chat-grading.component.spec.ts
  src/assets/wise5/components/peerChat/peer-chat-message/peer-chat-message.component.html
  src/assets/wise5/components/peerChat/peer-chat-message/peer-chat-message.component.spec.ts
  src/assets/wise5/components/peerChat/peer-chat-message/peer-chat-message.component.ts
  src/assets/wise5/components/peerChat/peer-chat-messages/peer-chat-messages.component.html
  src/assets/wise5/components/peerChat/peer-chat-messages/peer-chat-messages.component.scss
  src/assets/wise5/components/peerChat/peer-chat-messages/peer-chat-messages.component.ts
  src/assets/wise5/components/peerChat/peer-chat-previous-work/peer-chat-previous-work.component.html
  src/assets/wise5/components/peerChat/peer-chat-previous-work/peer-chat-previous-work.component.scss
  src/assets/wise5/components/peerChat/peer-chat-previous-work/peer-chat-previous-work.component.spec.ts
  src/assets/wise5/components/peerChat/peer-chat-previous-work/peer-chat-previous-work.component.ts
  src/assets/wise5/components/peerChat/peer-chat-question-bank/peer-chat-question-bank.component.html
  src/assets/wise5/components/peerChat/peer-chat-question-bank/peer-chat-question-bank.component.scss
  src/assets/wise5/components/peerChat/peer-chat-question-bank/peer-chat-question-bank.component.spec.ts
  src/assets/wise5/components/peerChat/peer-chat-question-bank/peer-chat-question-bank.component.ts
  src/assets/wise5/components/peerChat/peer-chat-student/peer-chat-student.component.html
  src/assets/wise5/components/peerChat/peer-chat-student/peer-chat-student.component.scss
  src/assets/wise5/components/peerChat/peer-chat-student/peer-chat-student.component.spec.ts
  src/assets/wise5/components/peerChat/peer-chat-student/peer-chat-student.component.ts
  src/assets/wise5/components/peerChat/peer-chat.module.ts
  src/messages.xlf
Labels: 1 point, 4 points

#417 chore(Authoring Tool): Convert branch authoring
  src/app/teacher/authoring-tool.module.ts
  src/assets/wise5/authoringTool/node/advanced/branch/node-advanced-branch-authoring.component.html
  src/assets/wise5/authoringTool/node/advanced/branch/node-advanced-branch-authoring.component.scss
  src/assets/wise5/authoringTool/node/advanced/branch/node-advanced-branch-authoring.component.ts
  src/assets/wise5/authoringTool/node/node-authoring.module.ts
  src/messages.xlf
Labels: 1 point

#408 feat(Peer Group): Implement teacher manual assignment view
  src/app/teacher-hybrid-angular.module.ts
  src/app/teacher/classroom-monitor.module.ts
  src/app/teacher/peer-group-grading.module.ts
  src/app/teacher/select-period.module.ts
  src/assets/wise5/classroomMonitor/classroomMonitorComponents/milestones/milestoneGradingView/milestoneGradingView.ts
  src/assets/wise5/classroomMonitor/classroomMonitorComponents/nodeGrading/nodeGrading.ts
  src/assets/wise5/classroomMonitor/classroomMonitorComponents/nodeGrading/nodeGradingView/nodeGradingView.html
  src/assets/wise5/classroomMonitor/classroomMonitorComponents/nodeGrading/nodeGradingView/nodeGradingView.ts
  src/assets/wise5/classroomMonitor/classroomMonitorComponents/peer-group/peer-group-assigned-workgroups/peer-group-assigned-workgroups.component.html
  src/assets/wise5/classroomMonitor/classroomMonitorComponents/peer-group/peer-group-assigned-workgroups/peer-group-assigned-workgroups.component.scss
  src/assets/wise5/classroomMonitor/classroomMonitorComponents/peer-group/peer-group-assigned-workgroups/peer-group-assigned-workgroups.component.spec.ts
  src/assets/wise5/classroomMonitor/classroomMonitorComponents/peer-group/peer-group-assigned-workgroups/peer-group-assigned-workgroups.component.ts
  src/assets/wise5/classroomMonitor/classroomMonitorComponents/peer-group/peer-group-dialog/peer-group-dialog.component.html
  src/assets/wise5/classroomMonitor/classroomMonitorComponents/peer-group/peer-group-dialog/peer-group-dialog.component.scss
  src/assets/wise5/classroomMonitor/classroomMonitorComponents/peer-group/peer-group-dialog/peer-group-dialog.component.spec.ts
  src/assets/wise5/classroomMonitor/classroomMonitorComponents/peer-group/peer-group-dialog/peer-group-dialog.component.ts
  src/assets/wise5/classroomMonitor/classroomMonitorComponents/peer-group/peer-group-grouping/peer-group-grouping.component.html
  src/assets/wise5/classroomMonitor/classroomMonitorComponents/peer-group/peer-group-grouping/peer-group-grouping.component.spec.ts
  src/assets/wise5/classroomMonitor/classroomMonitorComponents/peer-group/peer-group-grouping/peer-group-grouping.component.ts
  src/assets/wise5/classroomMonitor/classroomMonitorComponents/peer-group/peer-group-move-workgroup-confirm-dialog/peer-group-move-workgroup-confirm-dialog.component.html
  src/assets/wise5/classroomMonitor/classroomMonitorComponents/peer-group/peer-group-move-workgroup-confirm-dialog/peer-group-move-workgroup-confirm-dialog.component.scss
  src/assets/wise5/classroomMonitor/classroomMonitorComponents/peer-group/peer-group-move-workgroup-confirm-dialog/peer-group-move-workgroup-confirm-dialog.component.spec.ts
  src/assets/wise5/classroomMonitor/classroomMonitorComponents/peer-group/peer-group-move-workgroup-confirm-dialog/peer-group-move-workgroup-confirm-dialog.component.ts
  src/assets/wise5/classroomMonitor/classroomMonitorComponents/peer-group/peer-group-period/peer-group-period.component.html
  src/assets/wise5/classroomMonitor/classroomMonitorComponents/peer-group/peer-group-period/peer-group-period.component.scss
  src/assets/wise5/classroomMonitor/classroomMonitorComponents/peer-group/peer-group-period/peer-group-period.component.spec.ts
  src/assets/wise5/classroomMonitor/classroomMonitorComponents/peer-group/peer-group-period/peer-group-period.component.ts
  src/assets/wise5/classroomMonitor/classroomMonitorComponents/peer-group/peer-group-unassigned-workgroups/peer-group-unassigned-workgroups.component.html
  src/assets/wise5/classroomMonitor/classroomMonitorComponents/peer-group/peer-group-unassigned-workgroups/peer-group-unassigned-workgroups.component.spec.ts
  src/assets/wise5/classroomMonitor/classroomMonitorComponents/peer-group/peer-group-unassigned-workgroups/peer-group-unassigned-workgroups.component.ts
  src/assets/wise5/classroomMonitor/classroomMonitorComponents/peer-group/peer-group-workgroup/peer-group-workgroup.component.html
  src/assets/wise5/classroomMonitor/classroomMonitorComponents/peer-group/peer-group-workgroup/peer-group-workgroup.component.scss
  src/assets/wise5/classroomMonitor/classroomMonitorComponents/peer-group/peer-group-workgroup/peer-group-workgroup.component.spec.ts
  src/assets/wise5/classroomMonitor/classroomMonitorComponents/peer-group/peer-group-workgroup/peer-group-workgroup.component.ts
  src/assets/wise5/classroomMonitor/classroomMonitorComponents/peer-group/peer-group-workgroups-container/peer-group-workgroups-container.component.scss
  src/assets/wise5/classroomMonitor/classroomMonitorComponents/peer-group/peer-group-workgroups-container/peer-group-workgroups-container.component.ts
  src/assets/wise5/classroomMonitor/i18n/i18n_en.json
  src/assets/wise5/services/nodeService.ts
  src/assets/wise5/services/peerGroupService.ts
  src/assets/wise5/services/teacherDataService.ts
  src/assets/wise5/teacher/teacher-angular-js-module.ts
  src/messages.xlf
Labels: 1 point, 8 points

#423 feat(Peer Group): Make teacher view make requests to backend
  src/assets/wise5/classroomMonitor/classroomMonitorComponents/peer-group/peer-group-grouping/peer-group-grouping.component.html
  src/assets/wise5/classroomMonitor/classroomMonitorComponents/peer-group/peer-group-period/peer-group-period.component.spec.ts
  src/assets/wise5/classroomMonitor/classroomMonitorComponents/peer-group/peer-group-period/peer-group-period.component.ts
  src/assets/wise5/classroomMonitor/classroomMonitorComponents/peer-group/peer-group-unassigned-workgroups/peer-group-unassigned-workgroups.component.html
  src/assets/wise5/classroomMonitor/classroomMonitorComponents/peer-group/peer-group-workgroup/peer-group-workgroup.component.html
  src/assets/wise5/classroomMonitor/classroomMonitorComponents/peer-group/peer-group-workgroup/peer-group-workgroup.component.ts
  src/assets/wise5/services/peerGroupService.ts
Labels: 1 point

#425 feat(Peer Chat): Add manual grouping option to Peer Chat authoring
  src/assets/wise5/components/peerChat/peer-chat-authoring/peer-chat-authoring.component.html
  src/assets/wise5/components/peerChat/peer-chat-authoring/peer-chat-authoring.component.spec.ts
  src/assets/wise5/components/peerChat/peer-chat-authoring/peer-chat-authoring.component.ts
Labels: 1 point

#429 feat(Peer Group): Allow teacher to move workgroup to unassigned
  src/assets/wise5/classroomMonitor/classroomMonitorComponents/peer-group/peer-group-period/peer-group-period.component.spec.ts
  src/assets/wise5/classroomMonitor/classroomMonitorComponents/peer-group/peer-group-period/peer-group-period.component.ts
  src/assets/wise5/services/peerGroupService.ts
Labels: 1 point

#430 feat(Match): Update grading view to match student view
  src/app/teacher/component-grading.module.ts
  src/assets/wise5/components/match/delete-choice-button/delete-choice-button.component.html
  src/assets/wise5/components/match/delete-choice-button/delete-choice-button.component.scss
  src/assets/wise5/components/match/delete-choice-button/delete-choice-button.component.spec.ts
  src/assets/wise5/components/match/delete-choice-button/delete-choice-button.component.ts
  src/assets/wise5/components/match/match-choice-item/match-choice-item.component.html
  src/assets/wise5/components/match/match-choice-item/match-choice-item.component.scss
  src/assets/wise5/components/match/match-choice-item/match-choice-item.component.ts
  src/assets/wise5/components/match/match-common.module.ts
  src/assets/wise5/components/match/match-grading/match-grading-module.ts
  src/assets/wise5/components/match/match-grading/match-grading.component.html
  src/assets/wise5/components/match/match-grading/match-grading.component.scss
  src/assets/wise5/components/match/match-grading/match-grading.component.ts
  src/assets/wise5/components/match/match-status-icon/match-status-icon.component.html
  src/assets/wise5/components/match/match-status-icon/match-status-icon.component.ts
  src/assets/wise5/components/match/match-student/match-student.component.html
  src/assets/wise5/components/match/match-student/match-student.component.spec.ts
  src/assets/wise5/components/match/match-student/match-student.component.ts
  src/assets/wise5/components/match/match-student/match-student.module.ts
  src/assets/wise5/components/match/matchService.ts
  src/assets/wise5/style/fonts/roboto/fonts/sass/roboto.css.map
  src/assets/wise5/themes/default/style/angular-material.css
  src/assets/wise5/themes/default/style/angular-material.css.map
  src/assets/wise5/themes/default/style/author.css
  src/assets/wise5/themes/default/style/author.css.map
  src/assets/wise5/themes/default/style/author.scss
  src/assets/wise5/themes/default/style/modules/_component--match.scss
  src/assets/wise5/themes/default/style/monitor.css
  src/assets/wise5/themes/default/style/monitor.css.map
  src/assets/wise5/themes/default/style/monitor.scss
  src/assets/wise5/themes/default/style/vle.css
  src/assets/wise5/themes/default/style/vle.css.map
  src/assets/wise5/themes/default/style/vle.scss
  src/messages.xlf
Labels: 1 point

#432 feat(Peer Chat): Make logic authoring improvements
  src/assets/wise5/components/peerChat/peer-chat-authoring/peer-chat-authoring.component.html
  src/assets/wise5/components/peerChat/peer-chat-authoring/peer-chat-authoring.component.scss
  src/assets/wise5/components/peerChat/peer-chat-authoring/peer-chat-authoring.component.ts
  src/messages.xlf
Labels: 1 point

#433 fix(Export): Fix a bug that broke export because of unassigned student
  src/assets/wise5/classroomMonitor/dataExport/dataExportController.ts
Labels: 1 point

#435 feat(Authoring Tool): Convert NodeAdvancedPathAuthoring to Angular
  src/app/teacher/authoring-tool.module.ts
  src/assets/wise5/authoringTool/node/advanced/path/node-advanced-path-authoring.component.html
  src/assets/wise5/authoringTool/node/advanced/path/node-advanced-path-authoring.component.scss
  src/assets/wise5/authoringTool/node/advanced/path/node-advanced-path-authoring.component.spec.ts
  src/assets/wise5/authoringTool/node/advanced/path/node-advanced-path-authoring.component.ts
  src/assets/wise5/authoringTool/node/node-authoring.module.ts
  src/messages.xlf
Labels: 1 point

#439 feat(Error Handling): Filter errors from external requests
  src/app/http-error.interceptor.ts
  src/messages.xlf
Labels: 1 point
