Repository WISE-Community/WISE-Client, pull requests merged in 2021-08, with the labels that each got.

#284 Updated Manage Students UI
  src/app/http-error.interceptor.ts
  src/app/teacher/classroom-monitor.module.ts
  src/assets/wise5/classroomMonitor/classroomMonitorComponents/manageStudents/change-team-period-dialog/change-team-period-dialog.component.html
  src/assets/wise5/classroomMonitor/classroomMonitorComponents/manageStudents/change-team-period-dialog/change-team-period-dialog.component.spec.ts
  src/assets/wise5/classroomMonitor/classroomMonitorComponents/manageStudents/change-team-period-dialog/change-team-period-dialog.component.ts
  src/assets/wise5/classroomMonitor/classroomMonitorComponents/manageStudents/manage-period/manage-period.component.html
  src/assets/wise5/classroomMonitor/classroomMonitorComponents/manageStudents/manage-period/manage-period.component.scss
  src/assets/wise5/classroomMonitor/classroomMonitorComponents/manageStudents/manage-period/manage-period.component.spec.ts
  src/assets/wise5/classroomMonitor/classroomMonitorComponents/manageStudents/manage-period/manage-period.component.ts
  src/assets/wise5/classroomMonitor/classroomMonitorComponents/manageStudents/manage-show-student-info/manage-show-student-info.component.html
  src/assets/wise5/classroomMonitor/classroomMonitorComponents/manageStudents/manage-show-student-info/manage-show-student-info.component.scss
  src/assets/wise5/classroomMonitor/classroomMonitorComponents/manageStudents/manage-show-student-info/manage-show-student-info.component.spec.ts
  src/assets/wise5/classroomMonitor/classroomMonitorComponents/manageStudents/manage-show-student-info/manage-show-student-info.component.ts
  src/assets/wise5/classroomMonitor/classroomMonitorComponents/manageStudents/manage-students/manage-students.component.html
  src/assets/wise5/classroomMonitor/classroomMonitorComponents/manageStudents/manage-team/manage-team.component.html
  src/assets/wise5/classroomMonitor/classroomMonitorComponents/manageStudents/manage-team/manage-team.component.scss
  src/assets/wise5/classroomMonitor/classroomMonitorComponents/manageStudents/manage-team/manage-team.component.spec.ts
  src/assets/wise5/classroomMonitor/classroomMonitorComponents/manageStudents/manage-team/manage-team.component.ts
  src/assets/wise5/classroomMonitor/classroomMonitorComponents/manageStudents/manage-teams/manage-teams.component.html
  src/assets/wise5/classroomMonitor/classroomMonitorComponents/manageStudents/manage-teams/manage-teams.component.scss
  src/assets/wise5/classroomMonitor/classroomMonitorComponents/manageStudents/manage-teams/manage-teams.component.ts
  src/assets/wise5/classroomMonitor/classroomMonitorComponents/manageStudents/manage-user/manage-user.component.html
  src/assets/wise5/classroomMonitor/classroomMonitorComponents/manageStudents/move-user-confirm-dialog/move-user-confirm-dialog.component.html
  src/assets/wise5/themes/default/style/author.css
  src/assets/wise5/themes/default/style/author.css.map
  src/assets/wise5/themes/default/style/layouts/_l-default.scss
  src/assets/wise5/themes/default/style/monitor.css
  src/assets/wise5/themes/default/style/monitor.css.map
  src/assets/wise5/themes/default/style/vle.css
  src/assets/wise5/themes/default/style/vle.css.map
  src/messages.xlf
  src/style/abstracts/_mixins.scss
  src/style/abstracts/_variables.scss
  src/style/base/_typography.scss
Labels: 1 point

#278 Added subject and search text filter to Simulation Authoring
  src/assets/wise5/authoringTool/addNode/simulation/choose-item.html
  src/assets/wise5/authoringTool/addNode/simulation/simulationChooseItemController.ts
  src/assets/wise5/authoringTool/i18n/i18n_en.json
  src/assets/wise5/components/outsideURL/outside-url-authoring/outside-url-authoring.component.ts
  src/assets/wise5/i18n/i18n_en.json
Labels: 4 points

#288 Manage Students: Show all periods
  src/assets/wise5/classroomMonitor/classroomMonitorComponents/manageStudents/change-team-period-dialog/change-team-period-dialog.component.html
  src/assets/wise5/classroomMonitor/classroomMonitorComponents/manageStudents/manage-period/manage-period.component.html
  src/assets/wise5/classroomMonitor/classroomMonitorComponents/manageStudents/manage-show-student-info/manage-show-student-info.component.html
  src/assets/wise5/classroomMonitor/classroomMonitorComponents/manageStudents/manage-students/manage-students.component.html
  src/assets/wise5/classroomMonitor/classroomMonitorComponents/manageStudents/manage-students/manage-students.component.scss
  src/assets/wise5/classroomMonitor/classroomMonitorComponents/manageStudents/manage-students/manage-students.component.ts
  src/assets/wise5/classroomMonitor/classroomMonitorComponents/manageStudents/manage-students/manage-students.spec.ts
  src/messages.xlf
Labels: 1 point

#292 Change the add simulation view to display cards
  src/app/teacher/authoring-tool.module.ts
  src/assets/wise5/authoringTool/addNode/addNodeModule.ts
  src/assets/wise5/authoringTool/addNode/choose-new-node-template/choose-new-node-template.component.ts
  src/assets/wise5/authoringTool/addNode/simulation/choose-item.html
  src/assets/wise5/authoringTool/addNode/simulation/simulationChooseItemController.ts
  src/assets/wise5/authoringTool/components/card-selector/card-selector.component.html
  src/assets/wise5/authoringTool/components/card-selector/card-selector.component.scss
  src/assets/wise5/authoringTool/components/card-selector/card-selector.component.spec.ts
  src/assets/wise5/authoringTool/components/card-selector/card-selector.component.ts
  src/assets/wise5/authoringTool/i18n/i18n_en.json
  src/messages.xlf
Labels: 1 point

#290 manage students: remove student
  src/app/teacher/classroom-monitor.module.ts
  src/assets/wise5/classroomMonitor/classroomMonitorComponents/manageStudents/manage-team/manage-team.component.scss
  src/assets/wise5/classroomMonitor/classroomMonitorComponents/manageStudents/manage-user/manage-user.component.html
  src/assets/wise5/classroomMonitor/classroomMonitorComponents/manageStudents/manage-user/manage-user.component.scss
  src/assets/wise5/classroomMonitor/classroomMonitorComponents/manageStudents/manage-user/manage-user.component.spec.ts
  src/assets/wise5/classroomMonitor/classroomMonitorComponents/manageStudents/manage-user/manage-user.component.ts
  src/assets/wise5/classroomMonitor/classroomMonitorComponents/manageStudents/move-user-confirm-dialog/move-user-confirm-dialog.component.html
  src/assets/wise5/classroomMonitor/classroomMonitorComponents/manageStudents/remove-user-confirm-dialog/remove-user-confirm-dialog.component.html
  src/assets/wise5/classroomMonitor/classroomMonitorComponents/manageStudents/remove-user-confirm-dialog/remove-user-confirm-dialog.component.scss
  src/assets/wise5/classroomMonitor/classroomMonitorComponents/manageStudents/remove-user-confirm-dialog/remove-user-confirm-dialog.component.spec.ts
  src/assets/wise5/classroomMonitor/classroomMonitorComponents/manageStudents/remove-user-confirm-dialog/remove-user-confirm-dialog.component.ts
  src/messages.xlf
Labels: 1 point

#295 Remove ng-switch-default from component.ts and previewComponent.ts
  src/assets/wise5/authoringTool/components/preview-component/previewComponent.ts
  src/assets/wise5/components/componentController.ts
  src/assets/wise5/components/embedded/embedded-student/embedded-student.component.spec.ts
  src/assets/wise5/components/embedded/embedded-student/embedded-student.component.ts
  src/assets/wise5/components/graph/graph-student/graph-student.component.html
  src/assets/wise5/directives/component/component.ts
  src/assets/wise5/services/nodeService.ts
  src/assets/wise5/themes/default/style/author.css
  src/assets/wise5/themes/default/style/author.css.map
  src/assets/wise5/themes/default/style/modules/_component.scss
  src/assets/wise5/themes/default/style/monitor.css
  src/assets/wise5/themes/default/style/monitor.css.map
  src/assets/wise5/themes/default/style/vle.css
  src/assets/wise5/themes/default/style/vle.css.map
  src/assets/wise5/vle/node/nodeController.ts
Labels: 1 point

#296 Import work from previous step sometimes does not import
  src/assets/wise5/components/component-student.component.spec.ts
  src/assets/wise5/components/component-student.component.ts
  src/assets/wise5/components/discussion/discussion-student/discussion-student.component.spec.ts
  src/assets/wise5/components/discussion/discussion-student/discussion-student.component.ts
  src/assets/wise5/components/embedded/embedded-student/embedded-student.component.ts
  src/assets/wise5/components/graph/graph-student/graph-student.component.ts
Labels: 1 point

#297 Data explorer UI improvements
  src/assets/wise5/components/graph/graph-student/graph-student.component.html
  src/assets/wise5/components/graph/graph-student/graph-student.component.scss
  src/assets/wise5/components/graph/graph-student/graph-student.component.ts
  src/assets/wise5/components/table/table-student/table-student.component.html
  src/assets/wise5/components/table/table-student/table-student.component.scss
  src/messages.xlf
Labels: 1 point

#303 Thermo Challenge model graph bug
  src/assets/wise5/components/graph/graph-student/graph-student.component.ts
Labels: 1 point

#300 Refactor OpenResponse createComponentStateAdditionalProcessing
  src/assets/wise5/components/openResponse/open-response-student/open-response-student.component.ts
Labels: 1 point

#311 Fix ViewComponentRevisions dialog styles
  src/app/announcement/announcement.component.ts
  src/app/modules/library/community-library/community-library.component.ts
  src/app/modules/library/library-project-details/library-project-details.component.ts
  src/app/modules/library/library-project-menu/library-project-menu.component.ts
  src/app/modules/library/library-project/library-project.component.ts
  src/app/modules/library/official-library/official-library.component.ts
  src/app/modules/library/personal-library/personal-library.component.ts
  src/app/modules/library/share-project-dialog/share-project-dialog.component.html
  src/app/modules/library/teacher-project-library/teacher-project-library.component.ts
  src/app/modules/shared/edit-password/edit-password.component.ts
  src/app/modules/shared/unlink-google-account-confirm/unlink-google-account-confirm.component.ts
  src/app/modules/shared/unlink-google-account-password/unlink-google-account-password.component.html
  src/app/modules/shared/unlink-google-account-password/unlink-google-account-password.component.ts
  src/app/student/account/edit-profile/edit-profile.component.ts
  src/app/student/student-run-list-item/student-run-list-item.component.ts
  src/app/student/team-sign-in-dialog/team-sign-in-dialog.component.html
  src/app/student/team-sign-in-dialog/team-sign-in-dialog.component.scss
  src/app/teacher/account/edit-profile/edit-profile.component.ts
  src/app/teacher/create-run-dialog/create-run-dialog.component.html
  src/app/teacher/list-classroom-courses-dialog/list-classroom-courses-dialog.component.html
  src/app/teacher/run-menu/run-menu.component.ts
  src/app/teacher/run-settings-dialog/run-settings-dialog.component.html
  src/app/teacher/share-run-code-dialog/share-run-code-dialog.component.ts
  src/app/teacher/share-run-dialog/share-run-dialog.component.html
  src/app/teacher/teacher-run-list-item/teacher-run-list-item.component.ts
  src/app/teacher/teacher.service.ts
  src/app/teacher/use-with-class-warning-dialog/use-with-class-warning-dialog.component.ts
  src/assets/wise5/classroomMonitor/classroomMonitorComponents/shared/nodeIcon/node-icon.component.ts
  src/assets/wise5/classroomMonitor/classroomMonitorComponents/view-component-revisions/view-component-revisions.component.html
  src/assets/wise5/classroomMonitor/classroomMonitorComponents/workgroup-component-grading/workgroup-component-grading.component.ts
  src/assets/wise5/common/node-icon-chooser-dialog/node-icon-chooser-dialog.component.html
  src/assets/wise5/components/match/match-student/match-student.component.ts
  src/style/abstracts/_mixins.scss
  src/style/components/_dialog.scss
Labels: 1 point

#313 Removed unused code in OpenResponse component
  src/assets/wise5/components/openResponse/open-response-student/open-response-student.component.html
  src/assets/wise5/components/openResponse/open-response-student/open-response-student.component.spec.ts
  src/assets/wise5/components/openResponse/open-response-student/open-response-student.component.ts
Labels: 1 point

#309 Manage Students: create team and display unassigned students
  src/app/services/configService.spec.ts
  src/app/services/sampleData/sample_classmateUserInfos.json
  src/app/services/sampleData/sample_config_1.json
  src/app/services/updateWorkgroupService.ts
  src/app/services/workgroup.service.spec.ts
  src/app/services/workgroup.service.ts
  src/app/teacher/classroom-monitor.module.ts
  src/assets/wise5/classroomMonitor/classroomMonitorComponents/manageStudents/add-team-button/add-team-button.component.html
  src/assets/wise5/classroomMonitor/classroomMonitorComponents/manageStudents/add-team-button/add-team-button.component.scss
  src/assets/wise5/classroomMonitor/classroomMonitorComponents/manageStudents/add-team-button/add-team-button.component.ts
  src/assets/wise5/classroomMonitor/classroomMonitorComponents/manageStudents/add-team-dialog/add-team-dialog.component.html
  src/assets/wise5/classroomMonitor/classroomMonitorComponents/manageStudents/add-team-dialog/add-team-dialog.component.scss
  src/assets/wise5/classroomMonitor/classroomMonitorComponents/manageStudents/add-team-dialog/add-team-dialog.component.spec.ts
  src/assets/wise5/classroomMonitor/classroomMonitorComponents/manageStudents/add-team-dialog/add-team-dialog.component.ts
  src/assets/wise5/classroomMonitor/classroomMonitorComponents/manageStudents/change-team-period-dialog/change-team-period-dialog.component.html
  src/assets/wise5/classroomMonitor/classroomMonitorComponents/manageStudents/manage-period/manage-period.component.html
  src/assets/wise5/classroomMonitor/classroomMonitorComponents/manageStudents/manage-period/manage-period.component.scss
  src/assets/wise5/classroomMonitor/classroomMonitorComponents/manageStudents/manage-period/manage-period.component.spec.ts
  src/assets/wise5/classroomMonitor/classroomMonitorComponents/manageStudents/manage-period/manage-period.component.ts
  src/assets/wise5/classroomMonitor/classroomMonitorComponents/manageStudents/manage-team/manage-team.component.html
  src/assets/wise5/classroomMonitor/classroomMonitorComponents/manageStudents/manage-team/manage-team.component.scss
  src/assets/wise5/classroomMonitor/classroomMonitorComponents/manageStudents/manage-team/manage-team.component.ts
  src/assets/wise5/classroomMonitor/classroomMonitorComponents/manageStudents/manage-user/manage-user.component.html
  src/assets/wise5/classroomMonitor/classroomMonitorComponents/manageStudents/manage-user/manage-user.component.spec.ts
  src/assets/wise5/classroomMonitor/classroomMonitorComponents/manageStudents/manage-user/manage-user.component.ts
  src/assets/wise5/classroomMonitor/classroomMonitorComponents/manageStudents/move-user-confirm-dialog/move-user-confirm-dialog.component.html
  src/assets/wise5/classroomMonitor/classroomMonitorComponents/manageStudents/move-user-confirm-dialog/move-user-confirm-dialog.component.ts
  src/assets/wise5/classroomMonitor/classroomMonitorComponents/manageStudents/show-student-info/show-student-info.component.html
  src/assets/wise5/classroomMonitor/classroomMonitorComponents/manageStudents/show-student-info/show-student-info.component.scss
  src/assets/wise5/classroomMonitor/classroomMonitorComponents/manageStudents/show-student-info/show-student-info.component.spec.ts
  src/assets/wise5/classroomMonitor/classroomMonitorComponents/manageStudents/show-student-info/show-student-info.component.ts
  src/assets/wise5/services/configService.ts
  src/assets/wise5/services/teacherDataService.ts
  src/messages.xlf
Labels: 4 points, 8 points
