Repository WISE-Community/WISE-Client, pull requests merged in 2023-10, with the labels that each got.

#1439 refactor(NotificationService): getNewNotifications()
  src/assets/wise5/services/notificationService.ts
  src/messages.xlf
Labels: Code Quality

#1446 fix(Project Authoring): Can't go back into node authoring
  src/assets/wise5/authoringTool/project-authoring/project-authoring.component.ts
  src/messages.xlf
Labels: bug

#1428 refactor(RegisterUserFormComponent): Extract duplicate createAccountError()
  src/app/register/register-student-form/register-student-form.component.html
  src/app/register/register-student-form/register-student-form.component.spec.ts
  src/app/register/register-student-form/register-student-form.component.ts
  src/app/register/register-teacher-form/register-teacher-form.component.html
  src/app/register/register-teacher-form/register-teacher-form.component.spec.ts
  src/app/register/register-teacher-form/register-teacher-form.component.ts
  src/app/register/register-user-form/register-user-form.component.ts
  src/messages.xlf
Labels: Code Quality

#1454 refactor(NodeAuthoringComponent): Extract NodeAuthoringParentComponent
  src/app/teacher/authoring-routing.module.ts
  src/app/teacher/authoring-tool.module.ts
  src/assets/wise5/authoringTool/node/advanced/branch/node-advanced-branch-authoring.component.ts
  src/assets/wise5/authoringTool/node/advanced/constraint/node-advanced-constraint-authoring.component.spec.ts
  src/assets/wise5/authoringTool/node/advanced/constraint/node-advanced-constraint-authoring.component.ts
  src/assets/wise5/authoringTool/node/advanced/general/node-advanced-general-authoring.component.ts
  src/assets/wise5/authoringTool/node/advanced/json/node-advanced-json-authoring.component.ts
  src/assets/wise5/authoringTool/node/advanced/node-advanced-authoring/node-advanced-authoring.component.html
  src/assets/wise5/authoringTool/node/advanced/path/node-advanced-path-authoring.component.spec.ts
  src/assets/wise5/authoringTool/node/advanced/path/node-advanced-path-authoring.component.ts
  src/assets/wise5/authoringTool/node/editRubric/edit-node-rubric.component.spec.ts
  src/assets/wise5/authoringTool/node/editRubric/edit-node-rubric.component.ts
  src/assets/wise5/authoringTool/node/node-authoring-parent/node-authoring-parent.component.html
  src/assets/wise5/authoringTool/node/node-authoring-parent/node-authoring-parent.component.ts
  src/assets/wise5/authoringTool/node/node-authoring/node-authoring.component.html
  src/assets/wise5/authoringTool/node/node-authoring/node-authoring.component.ts
  src/messages.xlf
Labels: Code Quality

#1453 refactor(NodeService): Clean up getNextNode() for AT/CM modes
  src/assets/wise5/services/nodeService.ts
Labels: Code Quality

#1458 refactor(NodeService): Move authoring-specific observables to TeacherNodeService
  src/app/authoring-tool/edit-advanced-component/edit-advanced-component.component.ts
  src/assets/wise5/authoringTool/components/AbstractComponentAuthoring.ts
  src/assets/wise5/authoringTool/components/save-starter-state/save-starter-state.component.ts
  src/assets/wise5/authoringTool/node/node-authoring/node-authoring.component.spec.ts
  src/assets/wise5/authoringTool/node/node-authoring/node-authoring.component.ts
  src/assets/wise5/components/animation/animation-authoring/animation-authoring.component.spec.ts
  src/assets/wise5/components/animation/animation-authoring/animation-authoring.component.ts
  src/assets/wise5/components/audioOscillator/audio-oscillator-authoring/audio-oscillator-authoring.component.spec.ts
  src/assets/wise5/components/audioOscillator/audio-oscillator-authoring/audio-oscillator-authoring.component.ts
  src/assets/wise5/components/conceptMap/concept-map-authoring/concept-map-authoring.component.ts
  src/assets/wise5/components/conceptMap/concept-map-authoring/concept-map-authoring.module.ts
  src/assets/wise5/components/conceptMap/edit-concept-map-advanced/edit-concept-map-advanced.component.spec.ts
  src/assets/wise5/components/conceptMap/edit-concept-map-advanced/edit-concept-map-advanced.component.ts
  src/assets/wise5/components/dialogGuidance/dialog-guidance-authoring/dialog-guidance-authoring.component.spec.ts
  src/assets/wise5/components/dialogGuidance/dialog-guidance-authoring/dialog-guidance-authoring.component.ts
  src/assets/wise5/components/discussion/discussion-authoring/discussion-authoring.component.ts
  src/assets/wise5/components/draw/draw-authoring/draw-authoring.component.ts
  src/assets/wise5/components/draw/draw-authoring/draw-authoring.module.ts
  src/assets/wise5/components/embedded/embedded-authoring/embedded-authoring.component.spec.ts
  src/assets/wise5/components/embedded/embedded-authoring/embedded-authoring.component.ts
  src/assets/wise5/components/graph/edit-graph-advanced/edit-graph-advanced.component.spec.ts
  src/assets/wise5/components/graph/graph-authoring/graph-authoring.component.spec.ts
  src/assets/wise5/components/graph/graph-authoring/graph-authoring.component.ts
  src/assets/wise5/components/html/html-authoring/html-authoring.component.ts
  src/assets/wise5/components/label/label-authoring/label-authoring.component.ts
  src/assets/wise5/components/match/match-authoring/match-authoring.component.ts
  src/assets/wise5/components/multipleChoice/multiple-choice-authoring/multiple-choice-authoring.component.ts
  src/assets/wise5/components/openResponse/edit-open-response-advanced/edit-open-response-advanced.component.spec.ts
  src/assets/wise5/components/openResponse/edit-open-response-advanced/edit-open-response-advanced.component.ts
  src/assets/wise5/components/outsideURL/outside-url-authoring/outside-url-authoring.component.ts
  src/assets/wise5/components/peerChat/edit-peer-chat-advanced-component/edit-peer-chat-advanced-component.component.spec.ts
  src/assets/wise5/components/peerChat/edit-peer-chat-advanced-component/edit-peer-chat-advanced-component.component.ts
  src/assets/wise5/components/peerChat/peer-chat-authoring/peer-chat-authoring.component.spec.ts
  src/assets/wise5/components/peerChat/peer-chat-authoring/peer-chat-authoring.component.ts
  src/assets/wise5/components/showGroupWork/show-group-work-authoring/show-group-work-authoring.component.spec.ts
  src/assets/wise5/components/showGroupWork/show-group-work-authoring/show-group-work-authoring.component.ts
  src/assets/wise5/components/showMyWork/show-my-work-authoring/show-my-work-authoring.component.spec.ts
  src/assets/wise5/components/showMyWork/show-my-work-authoring/show-my-work-authoring.component.ts
  src/assets/wise5/components/summary/summary-authoring/summary-authoring.component.spec.ts
  src/assets/wise5/components/summary/summary-authoring/summary-authoring.component.ts
  src/assets/wise5/components/table/edit-table-advanced/edit-table-advanced.component.spec.ts
  src/assets/wise5/components/table/edit-table-advanced/edit-table-advanced.component.ts
  src/assets/wise5/components/table/table-authoring/table-authoring.component.ts
  src/assets/wise5/services/nodeService.ts
  src/assets/wise5/services/teacherNodeService.ts
  src/messages.xlf
Labels: Code Quality

#1459 refactor(NodeService): Remove scrollToComponentAndHighlight()
  src/app/services/wiseLinkService.ts
  src/assets/wise5/common/dom/dom.ts
  src/assets/wise5/services/nodeService.ts
Labels: Code Quality

#1460 refactor(TeacherDataService): Clean up pause period code
  src/assets/wise5/classroomMonitor/classroomMonitorComponents/shared/top-bar/top-bar.component.ts
  src/assets/wise5/services/teacherDataService.ts
  src/messages.xlf
Labels: Code Quality

#1461 refactor(Annotation): Create Annotation class
  src/app/classroom-monitor/component-new-work-badge/component-new-work-badge.component.ts
  src/app/classroom-monitor/milestones/milestones.component.ts
  src/app/notebook/notebook-report/notebook-report.component.ts
  src/assets/wise5/classroomMonitor/classroomMonitorComponents/edit-component-annotations/edit-component-annotations.component.ts
  src/assets/wise5/classroomMonitor/classroomMonitorComponents/milestones/milestone-grading-view/milestone-grading-view.component.ts
  src/assets/wise5/classroomMonitor/classroomMonitorComponents/nodeGrading/node-grading-view/node-grading-view.component.ts
  src/assets/wise5/classroomMonitor/student-grading/student-grading.component.ts
  src/assets/wise5/common/Annotation.ts
  src/assets/wise5/components/component-student.component.ts
  src/assets/wise5/components/openResponse/open-response-student/open-response-student.component.ts
  src/assets/wise5/services/annotationService.ts
  src/assets/wise5/services/notebookService.ts
  src/assets/wise5/services/studentDataService.ts
  src/assets/wise5/services/studentWebSocketService.ts
  src/assets/wise5/services/teacherDataService.ts
  src/assets/wise5/services/teacherWebSocketService.ts
  src/messages.xlf
Labels: Code Quality

#1463 refactor(StudentRunListComponent): Remove duplication
  src/app/domain/run.spec.ts
  src/app/domain/run.ts
  src/app/student/student-run-list/student-run-list.component.html
  src/app/student/student-run-list/student-run-list.component.ts
  src/app/teacher/teacher-run-list/teacher-run-list.component.spec.ts
  src/app/teacher/teacher-run-list/teacher-run-list.component.ts
Labels: Code Quality

#1443 refactor(ProjectLibraryService): getLibraryProjects() returns Observable
  src/app/authoring-tool/import-step/choose-import-unit/choose-import-unit.component.ts
  src/app/services/projectLibraryService.spec.ts
  src/assets/wise5/authoringTool/importComponent/choose-import-component/choose-import-component.component.ts
  src/assets/wise5/services/projectLibraryService.ts
  src/messages.xlf
Labels: Code Quality

#1464 refactor(TeacherDataService): retrieveRunStatus() returns Observable
  src/assets/wise5/services/teacherDataService.ts
  src/messages.xlf
Labels: Code Quality

#1469 refactor(AnnotationService): getLatestScoreAnnotation()
  src/app/classroom-monitor/component-new-work-badge/component-new-work-badge.component.ts
  src/app/services/annotationService.spec.ts
  src/app/services/studentPeerGroupService.spec.ts
  src/assets/wise5/common/constraint/strategies/ScoreConstraintStrategy.spec.ts
  src/assets/wise5/services/annotationService.ts
Labels: Code Quality

#1471 refactor(Project Authoring): Clean up template using node-icon-and-title
  src/assets/wise5/authoringTool/project-authoring/project-authoring.component.html
  src/messages.xlf
Labels: Code Quality

#1472 refactor(Component Grading): Introduce ComponentGradingComponent
  src/app/teacher/component-grading.module.ts
  src/assets/wise5/classroomMonitor/classroomMonitorComponents/component-grading.component.ts
  src/assets/wise5/classroomMonitor/classroomMonitorComponents/view-component-revisions/view-component-revisions.component.html
  src/assets/wise5/classroomMonitor/classroomMonitorComponents/workgroup-component-grading/workgroup-component-grading.component.html
  src/assets/wise5/components/Components.ts
  src/messages.xlf
Labels: Code Quality

#1470 refactor(NodeService): getNextNodeId()
  src/app/services/studentNodeService.spec.ts
  src/app/services/teacherNodeService.spec.ts
  src/assets/wise5/services/nodeService.ts
  src/assets/wise5/services/studentNodeService.ts
  src/assets/wise5/services/teacherNodeService.ts
Labels: Code Quality

#1480 refactor(StudentDataService): Clean up code
  src/app/services/studentDataService.spec.ts
  src/assets/wise5/services/studentDataService.ts
Labels: Code Quality

#1479 feat(Unit Authoring): Move advanced settings button to side menu
  src/assets/wise5/authoringTool/advanced/advanced-project-authoring.component.html
  src/assets/wise5/authoringTool/authoring-tool.component.ts
  src/assets/wise5/authoringTool/project-authoring/project-authoring.component.html
  src/assets/wise5/authoringTool/project-authoring/project-authoring.component.ts
  src/messages.xlf
Labels: enhancement

#1481 refactor(AnnotationService): Rewrite functions using declarative syntax
  src/assets/wise5/services/annotationService.ts
Labels: Code Quality

#1473 refactor(Project Authoring): Clean up template
  src/assets/wise5/authoringTool/project-authoring/project-authoring.component.html
  src/assets/wise5/authoringTool/project-authoring/project-authoring.component.scss
  src/assets/wise5/authoringTool/project-authoring/project-authoring.component.ts
  src/messages.xlf
Labels: Code Quality

#1485 refactor(DiscussionShowWorkComponent): Extract common function to show/hide posts
  src/assets/wise5/components/discussion/discussion-show-work/discussion-show-work.component.html
  src/assets/wise5/components/discussion/discussion-show-work/discussion-show-work.component.ts
Labels: Code Quality

#1484 refactor(AnnotationService): Move isThereAnyScoreAnnotation() to NodeInfo
  src/assets/wise5/classroomMonitor/classroomMonitorComponents/shared/node-info/node-info.component.ts
  src/assets/wise5/services/annotationService.ts
Labels: Code Quality

#1491 style(Preview Button): Change mat-icon value to preview
  src/app/authoring-tool/import-step/choose-import-step/choose-import-step.component.html
  src/app/modules/library/library-project-details/library-project-details.component.html
  src/app/student/student-run-list-item/student-run-list-item.component.html
  src/app/teacher/run-menu/run-menu.component.html
  src/assets/wise5/authoringTool/addNode/choose-automated-assessment/choose-automated-assessment.component.html
  src/assets/wise5/authoringTool/components/preview-component-button/preview-component-button.component.html
  src/assets/wise5/authoringTool/components/top-bar/top-bar.component.html
  src/assets/wise5/authoringTool/importComponent/choose-import-component/choose-import-component.component.html
  src/assets/wise5/authoringTool/node/node-authoring/node-authoring.component.html
  src/assets/wise5/authoringTool/project-list/project-list.component.html
  src/assets/wise5/classroomMonitor/classroomMonitorComponents/shared/top-bar/top-bar.component.html
  src/messages.xlf
Labels: enhancement

#1496 refactor(NodeService): Clean up getPrevNodeId() for AT/CM modes
  src/assets/wise5/services/nodeService.ts
Labels: Code Quality

#1487 refactor(FAQ): Extract common code to parent
  src/app/app.component.scss
  src/app/app.module.ts
  src/app/help/faq/faq.component.ts
  src/app/help/faq/getting-started/getting-started.component.html
  src/app/help/faq/getting-started/getting-started.component.spec.ts
  src/app/help/faq/getting-started/getting-started.component.ts
  src/app/help/faq/student-faq/student-faq.component.html
  src/app/help/faq/student-faq/student-faq.component.spec.ts
  src/app/help/faq/student-faq/student-faq.component.ts
  src/app/help/faq/teacher-faq/teacher-faq.component.html
  src/app/help/faq/teacher-faq/teacher-faq.component.spec.ts
  src/app/help/faq/teacher-faq/teacher-faq.component.ts
  src/app/help/getting-started/getting-started.component.scss
  src/app/help/getting-started/getting-started.component.ts
  src/app/help/help-routing.module.ts
  src/app/help/help.module.ts
  src/app/help/student-faq/student-faq.component.scss
  src/app/help/student-faq/student-faq.component.ts
  src/app/help/teacher-faq/teacher-faq.component.scss
  src/app/help/teacher-faq/teacher-faq.component.ts
  src/messages.xlf
Labels: Code Quality

#1497 refactor(AnnotationService): Move getAllLatestScoreAnnotations() to MilestoneReportService
  src/assets/wise5/services/annotationService.ts
  src/assets/wise5/services/milestoneReportService.ts
Labels: Code Quality

#1498 refactor(NodeService): Remove currentNodeHasTransitionLogic()
  src/assets/wise5/services/nodeService.ts
  src/assets/wise5/vle/node/node.component.ts
Labels: Code Quality

#1499 refactor(StudentDataService): Move getNotebookItemsByNodeId()
  src/app/services/studentDataService.spec.ts
  src/assets/wise5/common/constraint/strategies/AddXNumberOfNotesOnThisStepConstraintStrategy.ts
  src/assets/wise5/services/studentDataService.ts
  src/messages.xlf
Labels: Code Quality
