Repository WISE-Community/WISE-Client, pull requests merged in 2024-02, with the labels that each got.

#1618 refactor(TranslatableInput): Use two inputs instead of content projection
  src/assets/wise5/authoringTool/components/translatable-input/translatable-input.component.html
  src/assets/wise5/authoringTool/components/translatable-input/translatable-input.component.ts
  src/assets/wise5/components/match/match-authoring/match-authoring.component.html
  src/assets/wise5/components/multipleChoice/multiple-choice-authoring/multiple-choice-authoring.component.html
  src/messages.xlf
Labels: 2 points

#1624 feat(Speech to Text): Add SpeechToTextComponent and add to Open Response
  package-lock.json
  package.json
  src/app/classroom-monitor/show-node-info-dialog/show-node-info-dialog.component.spec.ts
  src/assets/wise5/components/openResponse/open-response-student/open-response-student.component.html
  src/assets/wise5/components/openResponse/open-response-student/open-response-student.component.spec.ts
  src/assets/wise5/components/openResponse/open-response-student/open-response-student.component.ts
  src/assets/wise5/components/openResponse/open-response-student/open-response-student.module.ts
  src/assets/wise5/components/openResponse/speech-to-text/speech-to-text.component.html
  src/assets/wise5/components/openResponse/speech-to-text/speech-to-text.component.scss
  src/assets/wise5/components/openResponse/speech-to-text/speech-to-text.component.spec.ts
  src/assets/wise5/components/openResponse/speech-to-text/speech-to-text.component.ts
  src/assets/wise5/services/projectService.ts
  src/assets/wise5/services/transcribeService.ts
  src/messages.xlf
Labels: 16 points

#1627 feat(Authoring Tool): Create TranslatableTextareaComponent
  src/app/authoring-tool/edit-component-prompt/edit-component-prompt.component.html
  src/app/teacher/component-authoring.module.ts
  src/assets/wise5/authoringTool/components/translatable-textarea/translatable-textarea.component.html
  src/assets/wise5/authoringTool/components/translatable-textarea/translatable-textarea.component.spec.ts
  src/assets/wise5/authoringTool/components/translatable-textarea/translatable-textarea.component.ts
  src/assets/wise5/components/component-authoring.module.ts
  src/messages.xlf
Labels: 4 points

#1634 feat(Speech to Text): Ensure only one component on a step is recording
  src/assets/wise5/components/openResponse/speech-to-text/speech-to-text.component.html
  src/assets/wise5/components/openResponse/speech-to-text/speech-to-text.component.ts
  src/assets/wise5/services/transcribeService.ts
  src/messages.xlf
Labels: 2 points

#1632 feat(Multiple Languages): Save new translations
  src/assets/wise5/authoringTool/components/abstract-translatable-field/abstract-translatable-field.component.ts
Labels: 4 points

#1635 feat(Speech to Text): Persist language selection across components
  src/assets/wise5/components/openResponse/speech-to-text/speech-to-text.component.html
  src/assets/wise5/components/openResponse/speech-to-text/speech-to-text.component.ts
  src/assets/wise5/services/transcribeService.ts
  src/messages.xlf
Labels: 2 points

#1654 refactor(Classroom Monitor): reduce duplication in StudentProgress
  src/assets/wise5/classroomMonitor/student-progress/student-progress.component.ts
  src/messages.xlf
Labels: Code Quality
