Repository WISE-Community/WISE-Client, pull requests merged in 2024-09, with the labels that each got.

#1932 chore(Canvg): Upgrade to v4.0
  package-lock.json
  package.json
  src/assets/wise5/components/graph/graph-student/graph-student.component.ts
Labels: build

#1933 refactor(ProjectService): getAllPaths()
  src/assets/wise5/classroomMonitor/dataExport/export-events/export-events.component.spec.ts
  src/assets/wise5/classroomMonitor/dataExport/export-one-workgroup-per-row/export-one-workgroup-per-row.component.spec.ts
  src/assets/wise5/classroomMonitor/dataExport/export-raw-data/export-raw-data.component.spec.ts
  src/assets/wise5/classroomMonitor/dataExport/export-student-work/export-student-work.component.spec.ts
  src/assets/wise5/services/projectService.ts
Labels: Code Quality

#1937 fix(Multilingual Unit): Component content doesn't update when changing language
  src/assets/wise5/vle/node/node.component.html
Labels: bug

#1938 refactor(NotebookNotesComponent): Convert to standalone
  src/app/notebook/notebook-notes/notebook-notes.component.html
  src/app/notebook/notebook-notes/notebook-notes.component.spec.ts
  src/app/notebook/notebook-notes/notebook-notes.component.ts
  src/app/notebook/notebook.module.ts
  src/assets/wise5/classroomMonitor/classroomMonitorComponents/notebook/notebook-workgroup-grading/notebook-workgroup-grading.component.html
  src/assets/wise5/vle/vle.component.html
  src/assets/wise5/vle/vle.component.spec.ts
  src/messages.xlf
Labels: Code Quality

#1939 fix(CM): Pausing/unpausing lessons does not persist to DB
  src/assets/wise5/classroomMonitor/classroomMonitorComponents/nodeProgress/nav-item/nav-item.component.spec.ts
  src/assets/wise5/classroomMonitor/classroomMonitorComponents/nodeProgress/nav-item/nav-item.component.ts
  src/messages.xlf
Labels: bug

#1945 fix(EmbeddedComponent): Break up i18n block in authoring
  src/assets/wise5/components/embedded/embedded-authoring/embedded-authoring.component.html
  src/locale/messages.ar.xlf
  src/locale/messages.de.xlf
  src/locale/messages.el.xlf
  src/locale/messages.es.xlf
  src/locale/messages.fa.xlf
  src/locale/messages.fr.xlf
  src/locale/messages.he.xlf
  src/locale/messages.it.xlf
  src/locale/messages.ja.xlf
  src/locale/messages.ko.xlf
  src/locale/messages.nl.xlf
  src/locale/messages.pt.xlf
  src/locale/messages.th.xlf
  src/locale/messages.tr.xlf
  src/locale/messages.vi.xlf
  src/locale/messages.zh-Hans.xlf
  src/locale/messages.zh-Hant.xlf
  src/messages.xlf
Labels: bug, build

#1941 refactor(Authoring Tool): Remove old branch authoring route and component
  src/app/teacher/authoring-routing.module.ts
  src/assets/wise5/authoringTool/components/shared/authoring-tool-bar/authoring-tool-bar.component.ts
  src/assets/wise5/authoringTool/node/advanced/branch/node-advanced-branch-authoring.component.html
  src/assets/wise5/authoringTool/node/advanced/branch/node-advanced-branch-authoring.component.scss
  src/assets/wise5/authoringTool/node/advanced/branch/node-advanced-branch-authoring.component.ts
  src/assets/wise5/authoringTool/node/advanced/node-advanced-authoring.module.ts
  src/assets/wise5/authoringTool/node/advanced/node-advanced-authoring/node-advanced-authoring.component.html
  src/messages.xlf
Labels: Code Quality, Low Priority

#1943 feat(a11y): Add keyboard accessibility to AT unit home
  src/app/teacher/authoring-tool.module.ts
  src/assets/wise5/authoringTool/project-authoring-lesson/project-authoring-lesson.component.html
  src/assets/wise5/authoringTool/project-authoring-lesson/project-authoring-lesson.component.scss
  src/assets/wise5/authoringTool/project-authoring-lesson/project-authoring-lesson.component.spec.ts
  src/assets/wise5/authoringTool/project-authoring-lesson/project-authoring-lesson.component.ts
  src/assets/wise5/authoringTool/project-authoring-lesson/project-authoring-lesson.harness.ts
  src/assets/wise5/authoringTool/project-authoring-step/project-authoring-step.component.html
  src/assets/wise5/authoringTool/project-authoring-step/project-authoring-step.component.scss
  src/assets/wise5/authoringTool/project-authoring-step/project-authoring-step.component.ts
  src/assets/wise5/authoringTool/project-authoring/project-authoring.component.html
  src/assets/wise5/authoringTool/project-authoring/project-authoring.component.scss
  src/assets/wise5/authoringTool/project-authoring/project-authoring.component.spec.ts
  src/messages.xlf
Labels: enhancement

#1947 refactor(NotebookReportAnnotationComponent): Remove unused class
  src/app/notebook/notebook-report-annotations/notebook-report-annotations.component.html
  src/app/notebook/notebook-report-annotations/notebook-report-annotations.component.spec.ts
  src/app/notebook/notebook-report-annotations/notebook-report-annotations.component.ts
  src/app/notebook/notebook-report/notebook-report.component.html
  src/app/notebook/notebook.module.ts
  src/messages.xlf
Labels: Code Quality

#1949 refactor(NotebookReportComponent): Convert to standalone
  src/app/notebook/notebook-report/notebook-report.component.html
  src/app/notebook/notebook-report/notebook-report.component.spec.ts
  src/app/notebook/notebook-report/notebook-report.component.ts
  src/app/notebook/notebook.module.ts
  src/assets/wise5/classroomMonitor/classroom-monitor.component.html
  src/assets/wise5/classroomMonitor/classroomMonitorComponents/notebook/notebook-workgroup-grading/notebook-workgroup-grading.component.html
  src/assets/wise5/vle/vle.component.html
  src/messages.xlf
Labels: Code Quality

#1950 feat(a11y): Add keyboard accessibility to AT node authoring
  src/assets/wise5/authoringTool/components/edit-component-advanced-button/edit-component-advanced-button.component.html
  src/assets/wise5/authoringTool/components/preview-component-button/preview-component-button.component.html
  src/assets/wise5/authoringTool/node/copy-component-button/copy-component-button.component.html
  src/assets/wise5/authoringTool/node/copy-component-button/copy-component-button.component.ts
  src/assets/wise5/authoringTool/node/node-authoring/node-authoring.component.html
  src/assets/wise5/authoringTool/node/node-authoring/node-authoring.component.scss
  src/assets/wise5/authoringTool/node/node-authoring/node-authoring.component.spec.ts
  src/assets/wise5/authoringTool/node/node-authoring/node-authoring.component.ts
  src/assets/wise5/authoringTool/project-authoring-lesson/project-authoring-lesson.component.scss
  src/messages.xlf
Labels: enhancement

#1951 refactor(VLEComponent): Convert to standalone
  src/app/student/vle/student-vle.module.ts
  src/assets/wise5/directives/safeUrl/safe-url.pipe.ts
  src/assets/wise5/vle/vle-parent/vle-parent.component.ts
  src/assets/wise5/vle/vle.component.html
  src/assets/wise5/vle/vle.component.spec.ts
  src/assets/wise5/vle/vle.component.ts
  src/messages.xlf
Labels: Code Quality, Low Priority

#1952 refactor(ChooseBranchPathDialogComponent): Convert to standalone
  src/app/preview/modules/choose-branch-path-dialog/choose-branch-path-dialog.component.html
  src/app/preview/modules/choose-branch-path-dialog/choose-branch-path-dialog.component.spec.ts
  src/app/preview/modules/choose-branch-path-dialog/choose-branch-path-dialog.component.ts
  src/app/student/vle/student-vle.module.ts
  src/assets/wise5/services/nodeService.ts
  src/assets/wise5/vle/vle.component.ts
  src/messages.xlf
Labels: Code Quality

#1953 refactor(ComponentAuthoringComponent): Convert to standalone
  src/app/teacher/component-authoring.module.ts
  src/assets/wise5/authoringTool/components/component-authoring.component.ts
  src/assets/wise5/authoringTool/node/node-authoring/node-authoring.component.html
Labels: Code Quality

#1954 refactor(EditComponentPromptComponent): Convert to standalone
  src/app/authoring-tool/edit-component-prompt/edit-component-prompt.component.ts
  src/app/teacher/component-authoring.module.ts
  src/assets/wise5/components/aiChat/ai-chat-authoring/ai-chat-authoring.component.spec.ts
  src/assets/wise5/components/animation/animation-authoring/animation-authoring.component.spec.ts
  src/assets/wise5/components/audioOscillator/audio-oscillator-authoring/audio-oscillator-authoring.component.spec.ts
  src/assets/wise5/components/conceptMap/concept-map-authoring/concept-map-authoring.module.ts
  src/assets/wise5/components/dialogGuidance/dialog-guidance-authoring/dialog-guidance-authoring.module.ts
  src/assets/wise5/components/draw/draw-authoring/draw-authoring.module.ts
  src/assets/wise5/components/embedded/embedded-authoring/embedded-authoring.module.ts
  src/assets/wise5/components/graph/graph-authoring/graph-authoring.component.spec.ts
  src/assets/wise5/components/multipleChoice/multiple-choice-authoring/multiple-choice-authoring.spec.ts
  src/assets/wise5/components/peerChat/peer-chat-authoring/peer-chat-authoring.component.spec.ts
  src/assets/wise5/components/showGroupWork/show-group-work-authoring/show-group-work-authoring.component.spec.ts
  src/assets/wise5/components/showMyWork/show-my-work-authoring/show-my-work-authoring.component.spec.ts
  src/assets/wise5/components/summary/summary-authoring/summary-authoring.component.spec.ts
Labels: Code Quality

#1955 refactor(EditComponentConstraintsComponent): Convert to standalone
  src/app/authoring-tool/edit-common-advanced/edit-common-advanced.component.html
  src/app/authoring-tool/edit-component-advanced/edit-component-advanced.component.html
  src/app/authoring-tool/edit-component-constraints/edit-component-constraints.component.html
  src/app/authoring-tool/edit-component-constraints/edit-component-constraints.component.spec.ts
  src/app/authoring-tool/edit-component-constraints/edit-component-constraints.component.ts
  src/app/teacher/component-authoring.module.ts
  src/assets/wise5/common/ComponentContent.ts
  src/assets/wise5/components/dialogGuidance/edit-dialog-guidance-advanced/edit-dialog-guidance-advanced.component.html
  src/assets/wise5/components/discussion/edit-discussion-advanced/edit-discussion-advanced.component.html
  src/assets/wise5/components/draw/edit-draw-advanced/edit-draw-advanced.component.html
  src/assets/wise5/components/graph/edit-graph-advanced/edit-graph-advanced.component.html
  src/assets/wise5/components/html/edit-html-advanced/edit-html-advanced.component.html
  src/assets/wise5/components/label/edit-label-advanced/edit-label-advanced.component.html
  src/assets/wise5/components/match/edit-match-advanced/edit-match-advanced.component.html
  src/assets/wise5/components/multipleChoice/edit-multiple-choice-advanced/edit-multiple-choice-advanced.component.html
  src/assets/wise5/components/outsideURL/edit-outside-url-advanced/edit-outside-url-advanced.component.html
  src/assets/wise5/components/peerChat/edit-peer-chat-advanced-component/edit-peer-chat-advanced-component.component.html
  src/assets/wise5/components/summary/edit-summary-advanced/edit-summary-advanced.component.html
  src/assets/wise5/components/table/edit-table-advanced/edit-table-advanced.component.html
  src/messages.xlf
Labels: Code Quality

#1956 refactor(EditComponentScoreComponent): Convert to standalone
  src/app/teacher/grading-common.module.ts
  src/assets/wise5/classroomMonitor/classroomMonitorComponents/edit-component-annotations/edit-component-annotations.component.html
  src/assets/wise5/classroomMonitor/classroomMonitorComponents/edit-component-score/edit-component-score.component.html
  src/assets/wise5/classroomMonitor/classroomMonitorComponents/edit-component-score/edit-component-score.component.spec.ts
  src/assets/wise5/classroomMonitor/classroomMonitorComponents/edit-component-score/edit-component-score.component.ts
  src/messages.xlf
Labels: Code Quality

#1957 refactor(GradingEditComponentMaxScore): Convert to standalone
  src/app/teacher/grading-common.module.ts
  src/assets/wise5/classroomMonitor/classroomMonitorComponents/edit-component-annotations/edit-component-annotations.component.html
  src/assets/wise5/classroomMonitor/classroomMonitorComponents/grading-edit-component-max-score/grading-edit-component-max-score.component.spec.ts
  src/assets/wise5/classroomMonitor/classroomMonitorComponents/grading-edit-component-max-score/grading-edit-component-max-score.component.ts
Labels: Code Quality
