Repository WISE-Community/WISE-Client, pull requests merged in 2025-03, with the labels that each got.

#2105 refactor(SummaryDisplay): Created classes for summary data
  src/app/services/summaryService.spec.ts
  src/assets/wise5/components/summary/summaryService.ts
  src/assets/wise5/directives/student-summary-display/student-summary-display.component.spec.ts
  src/assets/wise5/directives/student-summary-display/student-summary-display.component.ts
  src/assets/wise5/directives/summary-display/summary-data/MultipleChoiceSummaryData.ts
  src/assets/wise5/directives/summary-display/summary-data/MultipleChoiceSummaryDataPoint.ts
  src/assets/wise5/directives/summary-display/summary-data/ScoreSummaryData.ts
  src/assets/wise5/directives/summary-display/summary-data/ScoreSummaryDataPoint.ts
  src/assets/wise5/directives/summary-display/summary-data/SummaryData.ts
  src/assets/wise5/directives/summary-display/summary-data/SummaryDataPoint.ts
  src/assets/wise5/directives/summary-display/summary-data/TableSummaryData.ts
  src/assets/wise5/directives/summary-display/summary-data/TableSummaryDataPoint.ts
  src/assets/wise5/directives/summary-display/summary-display.component.ts
  src/assets/wise5/directives/teacher-summary-display/teacher-summary-display.component.ts
Labels: Code Quality

#2111 refactor(ComputerAvatarSelectorComponent): Convert to standalone
  src/assets/wise5/components/aiChat/ai-chat-student/ai-chat-student.component.html
  src/assets/wise5/components/aiChat/ai-chat-student/ai-chat-student.module.ts
  src/assets/wise5/components/dialogGuidance/dialog-guidance-student/dialog-guidance-student.component.html
  src/assets/wise5/components/dialogGuidance/dialogGuidanceStudentModule.ts
  src/assets/wise5/services/computerAvatarService.ts
  src/assets/wise5/vle/computer-avatar-selector/computer-avatar-selector.component.html
  src/assets/wise5/vle/computer-avatar-selector/computer-avatar-selector.component.spec.ts
  src/assets/wise5/vle/computer-avatar-selector/computer-avatar-selector.component.ts
  src/assets/wise5/vle/computer-avatar-selector/computer-avatar-selector.module.ts
  src/messages.xlf
Labels: Code Quality

#2108 build(Application): Remove Webpack dependencies
  package-lock.json
  package.json
  src/assets/wise5/services/peerGroupingAuthoringService.ts
Labels: build

#2110 refactor(SummaryDisplay): Refactor summary display
  src/app/domain/dummyComponentState.ts
  src/app/services/summaryService.spec.ts
  src/assets/wise5/common/DummyAnnotation.ts
  src/assets/wise5/common/SeriesData.ts
  src/assets/wise5/common/SeriesDataPoint.ts
  src/assets/wise5/components/summary/summaryService.ts
  src/assets/wise5/directives/student-summary-display/student-summary-display.component.spec.ts
  src/assets/wise5/directives/student-summary-display/student-summary-display.component.ts
  src/assets/wise5/directives/summary-display/summary-data/MultipleChoiceSummaryData.ts
  src/assets/wise5/directives/summary-display/summary-data/MultipleChoiceSummaryDataPoint.ts
  src/assets/wise5/directives/summary-display/summary-data/ScoreSummaryData.ts
  src/assets/wise5/directives/summary-display/summary-data/ScoreSummaryDataPoint.ts
  src/assets/wise5/directives/summary-display/summary-data/SummaryData.ts
  src/assets/wise5/directives/summary-display/summary-data/SummaryDataPoint.ts
  src/assets/wise5/directives/summary-display/summary-data/TableSummaryData.ts
  src/assets/wise5/directives/summary-display/summary-data/TableSummaryDataPoint.ts
  src/assets/wise5/directives/summary-display/summary-display.component.ts
  src/assets/wise5/directives/teacher-summary-display/teacher-summary-display.component.ts
  src/messages.xlf
Labels: Code Quality

#2113 feat(Grade By Component): Show component completion
  src/app/services/workgroup.service.ts
  src/assets/wise5/classroomMonitor/classroomMonitorComponents/component-completion/component-completion.component.spec.ts
  src/assets/wise5/classroomMonitor/classroomMonitorComponents/component-completion/component-completion.component.ts
  src/assets/wise5/classroomMonitor/classroomMonitorComponents/component-grading-view/component-grading-view.component.html
  src/assets/wise5/classroomMonitor/classroomMonitorComponents/component-grading-view/component-grading-view.component.ts
  src/messages.xlf
Labels: enhancement

#2124 refactor(LibraryProjectMenuComponent): Convert to standalone
  src/app/modules/library/library-project-menu/library-project-menu.component.html
  src/app/modules/library/library-project-menu/library-project-menu.component.spec.ts
  src/app/modules/library/library-project-menu/library-project-menu.component.ts
  src/app/modules/library/library.module.ts
  src/messages.xlf
Labels: Code Quality

#2125 refactor(LibraryProjectDetailsComponent): Convert to standalone
  src/app/modules/library/library-project-details/library-project-details.component.html
  src/app/modules/library/library-project-details/library-project-details.component.spec.ts
  src/app/modules/library/library-project-details/library-project-details.component.ts
  src/app/modules/library/library.module.ts
  src/messages.xlf
Labels: Code Quality

#2121 chore(gitignore): Added AWS files to .gitignore
  .gitignore
Labels: enhancement
