Repository WISE-Community/WISE-Client, pull requests merged in 2025-05, with the labels that each got.

#2160 feat(ProjectInfo): Let authors change the order of resources
  src/assets/wise5/authoringTool/edit-unit-resources/edit-unit-resources.component.html
  src/assets/wise5/authoringTool/edit-unit-resources/edit-unit-resources.component.scss
  src/assets/wise5/authoringTool/edit-unit-resources/edit-unit-resources.component.ts
  src/messages.xlf
Labels: enhancement

#2162 feat(Site): Remove unit library from teacher home
  src/app/app-routing.module.ts
  src/app/curriculum/curriculum.component.html
  src/app/curriculum/curriculum.component.scss
  src/app/curriculum/curriculum.component.spec.ts
  src/app/curriculum/curriculum.component.ts
  src/app/modules/header/header-links/header-links.component.html
  src/app/modules/header/header-links/header-links.component.spec.ts
  src/app/modules/header/header-links/header-links.component.ts
  src/app/modules/library/community-library/community-library.component.html
  src/app/modules/library/community-library/community-library.component.spec.ts
  src/app/modules/library/community-library/community-library.component.ts
  src/app/modules/library/library.module.ts
  src/app/modules/library/library/library.component.ts
  src/app/modules/library/official-library/official-library.component.html
  src/app/modules/library/official-library/official-library.component.spec.ts
  src/app/modules/library/official-library/official-library.component.ts
  src/app/modules/library/personal-library/personal-library-details.html
  src/app/modules/library/personal-library/personal-library.component.html
  src/app/modules/library/personal-library/personal-library.component.ts
  src/app/modules/library/personal-library/personal-library.harness.ts
  src/app/modules/library/public-library/public-library.component.ts
  src/app/modules/library/public-unit-type-selector/community-library-details.html
  src/app/modules/library/public-unit-type-selector/official-library-details.html
  src/app/modules/library/public-unit-type-selector/public-unit-type-selector.component.ts
  src/app/modules/library/teacher-project-library/teacher-project-library.component.html
  src/app/modules/library/teacher-project-library/teacher-project-library.component.scss
  src/app/modules/library/teacher-project-library/teacher-project-library.component.spec.ts
  src/app/modules/library/teacher-project-library/teacher-project-library.component.ts
  src/app/services/library.service.ts
  src/app/teacher/edit-run-warning-dialog/edit-run-warning-dialog.component.html
  src/app/teacher/teacher-home/teacher-home.component.html
  src/app/teacher/teacher-home/teacher-home.component.scss
  src/app/teacher/teacher-routing.module.ts
  src/app/teacher/teacher-run-list/teacher-run-list.component.html
  src/app/teacher/teacher-run-list/teacher-run-list.component.scss
  src/app/teacher/teacher-run-list/teacher-run-list.component.ts
  src/assets/wise5/classroomMonitor/classroomMonitorComponents/nodeGrading/node-grading/node-grading.component.html
  src/messages.xlf
Labels: enhancement

#2167 fix(Grading Tool): Hide detectable ideas if missing rubric data
  src/assets/wise5/components/common/cRater/CRaterRubric.ts
  src/assets/wise5/components/common/cRater/crater-rubric/crater-rubric.component.html
  src/assets/wise5/components/common/cRater/crater-rubric/crater-rubric.component.spec.ts
  src/assets/wise5/components/common/cRater/crater-rubric/crater-rubric.component.ts
  src/assets/wise5/components/dialogGuidance/dialog-guidance-show-work/dialog-guidance-show-work.component.spec.ts
  src/assets/wise5/components/dialogGuidance/dialog-responses/dialog-responses.component.html
  src/assets/wise5/components/dialogGuidance/dialog-responses/dialog-responses.component.ts
  src/messages.xlf
Labels: bug

#2172 refactor(Application): Remove unnecessary imports
  src/app/student/top-bar/top-bar.component.ts
  src/app/teacher/select-tags/select-tags.component.ts
  src/assets/wise5/authoringTool/components/component-type-button/component-type-button.component.ts
  src/assets/wise5/authoringTool/create-branch-paths/create-branch-paths.component.ts
  src/assets/wise5/authoringTool/teacher-node-icon/teacher-node-icon.component.ts
  src/assets/wise5/classroomMonitor/classroomMonitorComponents/component-grading.component.ts
  src/assets/wise5/components/dialogGuidance/dialog-responses/dialog-responses.component.ts
  src/assets/wise5/components/openResponse/open-response-authoring/open-response-authoring.component.html
  src/assets/wise5/vle/vle.component.ts
  src/messages.xlf
Labels: Code Quality

#2169 refactor(LibraryService): Move ProjectFilterValues out of class
  src/app/curriculum/curriculum.component.ts
  src/app/domain/projectFilterValues.ts
  src/app/modules/library/home-page-project-library/home-page-project-library.component.ts
  src/app/modules/library/library-filters/library-filters.component.html
  src/app/modules/library/library-filters/library-filters.component.spec.ts
  src/app/modules/library/library-filters/library-filters.component.ts
  src/app/modules/library/library/library.component.ts
  src/app/modules/library/official-library/official-library.component.spec.ts
  src/app/modules/library/official-library/official-library.component.ts
  src/app/modules/library/personal-library/personal-library.component.spec.ts
  src/app/modules/library/personal-library/personal-library.component.ts
  src/app/modules/library/public-library/public-library.component.spec.ts
  src/app/modules/library/public-unit-type-selector/public-unit-type-selector.component.spec.ts
  src/app/modules/library/public-unit-type-selector/public-unit-type-selector.component.ts
  src/app/services/library.service.ts
  src/messages.xlf
Labels: Code Quality

#2176 refactor(LibraryService): Move filterValuesUpdated to ProjectFilterValues
  src/app/curriculum/curriculum.component.spec.ts
  src/app/domain/projectFilterValues.ts
  src/app/modules/library/library-filters/library-filters.component.spec.ts
  src/app/modules/library/library-filters/library-filters.component.ts
  src/app/modules/library/library/library.component.ts
  src/app/modules/library/official-library/official-library.component.spec.ts
  src/app/modules/library/public-library/public-library.component.spec.ts
  src/app/services/library.service.ts
  src/app/teacher/teacher-home/teacher-home.component.spec.ts
  src/app/teacher/teacher-home/teacher-home.component.ts
  src/assets/wise5/authoringTool/new-project-template.ts
  src/messages.xlf
Labels: Code Quality

#2171 fix(OpenResponse): Show idea description authoring
  src/app/teacher/component-authoring.module.ts
Labels: bug

#2182 feat(Unit Info): Hide standard names and show in tooltip
  src/app/modules/library/library-project-details/library-project-details.component.html
  src/messages.xlf
  src/style/base/_base.scss
  src/style/styles.scss
Labels: enhancement

#2185 feat(Match): Filter out detected ideas from pre-authored choices #2184
  src/assets/wise5/components/match/match-student/match-student-default/match-student-default.component.ts
  src/messages.xlf
Labels: enhancement

#2186 chore(AuthoringToolComponent): Convert to standalone
  src/app/teacher/authoring-tool.module.ts
  src/assets/wise5/authoringTool/authoring-tool.component.html
  src/assets/wise5/authoringTool/authoring-tool.component.ts
  src/messages.xlf
Labels: Code Quality

#2164 feat(Match): Summary display
  src/app/services/summaryService.spec.ts
  src/assets/wise5/classroomMonitor/classroomMonitorComponents/shared/node-info/node-info.component.html
  src/assets/wise5/classroomMonitor/classroomMonitorComponents/shared/node-info/node-info.component.ts
  src/assets/wise5/components/summary/summaryService.ts
  src/assets/wise5/directives/teacher-summary-display/ideas-summary-display/ideas-summary.component.html
  src/assets/wise5/directives/teacher-summary-display/ideas-summary-display/ideas-summary.component.spec.ts
  src/assets/wise5/directives/teacher-summary-display/ideas-summary-display/ideas-summary.component.ts
  src/assets/wise5/directives/teacher-summary-display/match-summary-display/match-summary-display.component.html
  src/assets/wise5/directives/teacher-summary-display/match-summary-display/match-summary-display.component.scss
  src/assets/wise5/directives/teacher-summary-display/match-summary-display/match-summary-display.component.spec.ts
  src/assets/wise5/directives/teacher-summary-display/match-summary-display/match-summary-display.component.ts
  src/assets/wise5/directives/teacher-summary-display/summary-data/MatchSummaryData.ts
  src/assets/wise5/directives/teacher-summary-display/summary-data/MatchSummaryDataPoint.ts
  src/messages.xlf
Labels: enhancement

#2183 feat(ContactForm): Share units for community library
  src/app/contact/contact-form/contact-form.component.html
  src/app/contact/contact-form/contact-form.component.ts
  src/app/modules/library/library-project-details/library-project-details.component.html
  src/app/modules/library/library-project-details/library-project-details.component.spec.ts
  src/app/modules/library/library-project-details/library-project-details.component.ts
  src/app/modules/library/library-project-menu/library-project-menu.component.html
  src/app/modules/library/library-project-menu/library-project-menu.component.ts
  src/app/modules/library/public-unit-type-selector/community-library-details.html
  src/assets/wise5/authoringTool/project-info-authoring/project-info-authoring.component.html
  src/assets/wise5/authoringTool/project-info-authoring/project-info-authoring.component.scss
  src/assets/wise5/authoringTool/project-info-authoring/project-info-authoring.component.spec.ts
  src/assets/wise5/authoringTool/project-info-authoring/project-info-authoring.component.ts
  src/messages.xlf
Labels: enhancement

#2170 feat(AIChat): Connect to Open Response
  src/assets/wise5/components/aiChat/AiChatMessage.ts
  src/assets/wise5/components/aiChat/ai-chat-bot-message/ai-chat-bot-message.component.spec.ts
  src/assets/wise5/components/aiChat/ai-chat-messages/ai-chat-messages.component.html
  src/assets/wise5/components/aiChat/ai-chat-student-message/ai-chat-student-message.component.spec.ts
  src/assets/wise5/components/aiChat/ai-chat-student/ai-chat-student.component.spec.ts
  src/assets/wise5/components/aiChat/ai-chat-student/ai-chat-student.component.ts
  src/assets/wise5/components/aiChat/edit-ai-chat-advanced/edit-ai-chat-advanced.component.html
  src/assets/wise5/components/aiChat/edit-ai-chat-advanced/edit-ai-chat-advanced.component.spec.ts
  src/assets/wise5/components/aiChat/edit-ai-chat-advanced/edit-ai-chat-advanced.component.ts
  src/messages.xlf
Labels: enhancement
