Repository WISE-Community/WISE-Client, pull requests merged in 2025-04, with the labels that each got.

#2129 refactor(EditOpenResponseAdvancedComponent): Replace ngIf and ngFor statements
  src/assets/wise5/components/openResponse/edit-open-response-advanced/edit-open-response-advanced.component.html
  src/assets/wise5/components/openResponse/edit-open-response-advanced/edit-open-response-advanced.component.ts
  src/messages.xlf
Labels: Code Quality

#2116 build(Application): Generate messages when new PR is made
  .github/workflows/code-build.yml
  .github/workflows/develop-workflows.yml
  .github/workflows/generate-messages.yml
  .github/workflows/other-branch-workflows.yml
  .github/workflows/test-coverage.yml
  src/assets/wise5/components/openResponse/edit-open-response-advanced/edit-open-response-advanced.component.ts
Labels: enhancement, build

#2115 feat(Dialog Guidance): Summary display for teachers
  src/assets/wise5/classroomMonitor/classroomMonitorComponents/shared/node-info/node-info.component.html
  src/assets/wise5/classroomMonitor/classroomMonitorComponents/shared/node-info/node-info.component.scss
  src/assets/wise5/classroomMonitor/classroomMonitorComponents/shared/node-info/node-info.component.ts
  src/assets/wise5/components/common/cRater/CRaterRubric.ts
  src/assets/wise5/components/summary/summaryService.ts
  src/assets/wise5/directives/summary-display/summary-display.component.html
  src/assets/wise5/directives/summary-display/summary-display.component.scss
  src/assets/wise5/directives/teacher-summary-display/dialog-guidance-teacher-summary-display.component.html
  src/assets/wise5/directives/teacher-summary-display/dialog-guidance-teacher-summary-display.component.spec.ts
  src/assets/wise5/directives/teacher-summary-display/dialog-guidance-teacher-summary-display.component.ts
  src/messages.xlf
Labels: enhancement

#2134 fix(Session): Make renewSession requests on mouse move
  src/assets/wise5/vle/vle.component.ts
Labels: bug

#2130 feat(OpenResponse): Allow authors to specify student-friendly text for ideas
  src/assets/wise5/components/common/cRater/CRaterIdea.ts
  src/assets/wise5/components/common/cRater/edit-crater-idea-descriptions/edit-crater-idea-descriptions.component.html
  src/assets/wise5/components/common/cRater/edit-crater-idea-descriptions/edit-crater-idea-descriptions.component.ts
  src/assets/wise5/components/dialogGuidance/edit-dialog-guidance-advanced/edit-dialog-guidance-advanced.component.ts
  src/assets/wise5/components/openResponse/edit-open-response-advanced/edit-open-response-advanced.component.html
  src/assets/wise5/components/openResponse/edit-open-response-advanced/edit-open-response-advanced.component.ts
  src/messages.xlf
Labels: enhancement

#2137 feat(Metadata): Add standard and discipline fields
  src/app/domain/projectFilterValues.ts
  src/app/modules/library/Discipline.ts
  src/app/modules/library/ResearchProject.ts
  src/app/modules/library/community-library/community-library.component.spec.ts
  src/app/modules/library/library-filters/library-filters.component.html
  src/app/modules/library/library-filters/library-filters.component.spec.ts
  src/app/modules/library/library-filters/library-filters.component.ts
  src/app/modules/library/library-project-details/library-project-details.component.html
  src/app/modules/library/library-project-details/library-project-details.component.spec.ts
  src/app/modules/library/library-project-details/library-project-details.component.ts
  src/app/modules/library/library-project-disciplines/library-project-disciplines.component.ts
  src/app/modules/library/library.module.ts
  src/app/modules/library/library/library.component.ts
  src/app/modules/library/ngssStandards.ts
  src/app/modules/library/official-library/official-library.component.spec.ts
  src/app/modules/library/personal-library/personal-library.component.spec.ts
  src/app/modules/library/sampleLibraryProjects.ts
  src/app/modules/library/standard.ts
  src/app/modules/shared/standards-select-menu/standards-select-menu.component.html
  src/app/modules/shared/standards-select-menu/standards-select-menu.component.spec.ts
  src/app/modules/shared/standards-select-menu/standards-select-menu.component.ts
  src/messages.xlf
Labels: enhancement

#2138 chore(LibraryProjectComponent): Convert to standalone
  src/app/modules/library/library-project/library-project.component.html
  src/app/modules/library/library-project/library-project.component.spec.ts
  src/app/modules/library/library-project/library-project.component.ts
  src/app/modules/library/library.module.ts
  src/app/modules/library/personal-library/personal-library.component.spec.ts
  src/messages.xlf
Labels: Code Quality

#2135 feat(OpenResponse): Summary display for teachers
  src/app/services/ideasSortingService.spec.ts
  src/app/services/summaryService.spec.ts
  src/assets/wise5/classroomMonitor/classroomMonitorComponents/shared/node-info/node-info.component.html
  src/assets/wise5/classroomMonitor/classroomMonitorComponents/shared/node-info/node-info.component.ts
  src/assets/wise5/components/summary/summary-authoring/summary-authoring.component.spec.ts
  src/assets/wise5/components/summary/summaryService.ts
  src/assets/wise5/directives/teacher-summary-display/dialog-guidance-teacher-summary-display.component.spec.ts
  src/assets/wise5/directives/teacher-summary-display/dialog-guidance-teacher-summary-display.component.ts
  src/assets/wise5/directives/teacher-summary-display/ideas-summary.component.html
  src/assets/wise5/directives/teacher-summary-display/ideas-summary.component.spec.ts
  src/assets/wise5/directives/teacher-summary-display/ideas-summary.component.ts
  src/assets/wise5/directives/teacher-summary-display/summary-data/DialogGuidanceSummaryData.ts
  src/assets/wise5/directives/teacher-summary-display/summary-data/DialogGuidanceSummaryDataPoint.ts
  src/assets/wise5/directives/teacher-summary-display/summary-data/IdeasSummaryData.ts
  src/assets/wise5/directives/teacher-summary-display/summary-data/IdeasSummaryDataPoint.ts
  src/assets/wise5/directives/teacher-summary-display/summary-data/OpenResponseSummaryData.ts
  src/assets/wise5/directives/teacher-summary-display/summary-data/OpenResponseSummaryDataPoint.ts
  src/assets/wise5/services/cRaterService.ts
  src/assets/wise5/services/ideasSortingService.ts
  src/messages.xlf
Labels: enhancement

#2136 feat(Embedded): Grow model file name input vertically
  src/assets/wise5/components/embedded/embedded-authoring/embedded-authoring.component.html
  src/assets/wise5/components/embedded/embedded-authoring/embedded-authoring.component.scss
  src/messages.xlf
Labels: enhancement

#2152 fix(Unit Library): redesign fixes
  src/app/domain/projectFilterValues.ts
  src/app/modules/library/library-filters/library-filters.component.html
  src/app/modules/library/library-filters/library-filters.component.ts
  src/app/modules/library/library/library.component.ts
  src/app/modules/library/public-library/public-library.component.spec.ts
Labels: bug

#2149 fix(AT): Clicking lesson/step title does not check checkbox
  src/assets/wise5/authoringTool/project-authoring-lesson/project-authoring-lesson.component.html
  src/assets/wise5/authoringTool/project-authoring-step/project-authoring-step.component.html
  src/messages.xlf
Labels: bug

#2142 Fixed advanced editing on existing components with CRater enabled
  src/assets/wise5/components/openResponse/edit-open-response-advanced/edit-open-response-advanced.component.spec.ts
  src/assets/wise5/components/openResponse/edit-open-response-advanced/edit-open-response-advanced.component.ts
  src/messages.xlf
Labels: bug

#2155 test(EditOpenResponseAdvanced): Fixed failing test
  src/assets/wise5/components/openResponse/edit-open-response-advanced/edit-open-response-advanced.component.spec.ts
  src/assets/wise5/components/openResponse/edit-open-response-advanced/edit-open-response-advanced.component.ts
  src/messages.xlf
Labels: bug

#2140 feat(DialogGuidance): Show idea detection rubric in grading tool
  src/app/services/ideasSortingService.spec.ts
  src/assets/wise5/components/common/cRater/CRaterIdea.ts
  src/assets/wise5/components/common/cRater/IdeaData.ts
  src/assets/wise5/components/common/cRater/crater-rubric/RubricEventService.ts
  src/assets/wise5/components/common/cRater/crater-rubric/crater-rubric.component.html
  src/assets/wise5/components/common/cRater/crater-rubric/crater-rubric.component.scss
  src/assets/wise5/components/common/cRater/crater-rubric/crater-rubric.component.spec.ts
  src/assets/wise5/components/common/cRater/crater-rubric/crater-rubric.component.ts
  src/assets/wise5/components/dialogGuidance/dialog-responses/dialog-responses.component.html
  src/assets/wise5/components/dialogGuidance/dialog-responses/dialog-responses.component.scss
  src/assets/wise5/components/dialogGuidance/dialog-responses/dialog-responses.component.ts
  src/assets/wise5/directives/teacher-summary-display/ideas-summary.component.ts
  src/assets/wise5/services/ideasSortingService.ts
  src/messages.xlf
Labels: enhancement

#2158 feat(Curriculum): Add My Units tab
  src/app/curriculum/curriculum.component.html
  src/app/curriculum/curriculum.component.scss
  src/app/curriculum/curriculum.component.spec.ts
  src/app/curriculum/curriculum.component.ts
  src/app/modules/library/community-library/community-library.component.spec.ts
  src/app/modules/library/community-library/community-library.component.ts
  src/app/modules/library/library-project/library-project.component.html
  src/app/modules/library/library.module.ts
  src/app/modules/library/library/library.component.ts
  src/app/modules/library/official-library/official-library.component.spec.ts
  src/app/modules/library/official-library/official-library.component.ts
  src/app/modules/library/personal-library/personal-library.component.html
  src/app/modules/library/personal-library/personal-library.component.scss
  src/app/modules/library/personal-library/personal-library.component.spec.ts
  src/app/modules/library/personal-library/personal-library.component.ts
  src/app/modules/library/personal-library/personal-library.harness.ts
  src/app/modules/library/public-library/public-library.component.ts
  src/app/modules/library/teacher-project-library/teacher-project-library.component.spec.ts
  src/app/modules/library/teacher-project-library/teacher-project-library.component.ts
  src/app/services/config.service.ts
  src/app/services/library.service.ts
  src/app/teacher/select-tags/select-tags.component.ts
  src/messages.xlf
Labels: enhancement

#2139 feat(CRater): Add model description to rubric
  src/app/authoring-tool/edit-component-advanced/edit-component-advanced.component.html
  src/app/services/ideasSortingService.spec.ts
  src/app/teacher/component-authoring.module.ts
  src/assets/wise5/components/common/cRater/CRaterIdea.ts
  src/assets/wise5/components/common/cRater/CRaterRubric.ts
  src/assets/wise5/components/common/cRater/IdeaData.ts
  src/assets/wise5/components/common/cRater/crater-rubric/RubricEventService.ts
  src/assets/wise5/components/common/cRater/crater-rubric/crater-rubric.component.html
  src/assets/wise5/components/common/cRater/crater-rubric/crater-rubric.component.scss
  src/assets/wise5/components/common/cRater/crater-rubric/crater-rubric.component.spec.ts
  src/assets/wise5/components/common/cRater/crater-rubric/crater-rubric.component.ts
  src/assets/wise5/components/common/cRater/edit-crater-description/edit-crater-description.component.html
  src/assets/wise5/components/common/cRater/edit-crater-description/edit-crater-description.component.scss
  src/assets/wise5/components/common/cRater/edit-crater-description/edit-crater-description.component.spec.ts
  src/assets/wise5/components/common/cRater/edit-crater-description/edit-crater-description.component.ts
  src/assets/wise5/components/common/cRater/edit-crater-idea-descriptions/edit-crater-idea-descriptions.component.ts
  src/assets/wise5/components/common/cRater/edit-crater-info/edit-crater-info.component.html
  src/assets/wise5/components/common/cRater/edit-crater-info/edit-crater-info.component.scss
  src/assets/wise5/components/common/cRater/edit-crater-info/edit-crater-info.component.spec.ts
  src/assets/wise5/components/common/cRater/edit-crater-info/edit-crater-info.component.ts
  src/assets/wise5/components/dialogGuidance/dialog-responses/dialog-responses.component.html
  src/assets/wise5/components/dialogGuidance/dialog-responses/dialog-responses.component.scss
  src/assets/wise5/components/dialogGuidance/dialog-responses/dialog-responses.component.ts
  src/assets/wise5/components/dialogGuidance/edit-dialog-guidance-advanced/edit-dialog-guidance-advanced.component.html
  src/assets/wise5/components/dialogGuidance/edit-dialog-guidance-advanced/edit-dialog-guidance-advanced.component.ts
  src/assets/wise5/directives/teacher-summary-display/ideas-summary.component.ts
  src/assets/wise5/services/ideasSortingService.ts
  src/messages.xlf
Labels: enhancement

#2161 refactor(Unit Library): Share FilterValues in LibraryService
  src/app/curriculum/curriculum.component.spec.ts
  src/app/curriculum/curriculum.component.ts
  src/app/modules/library/community-library/community-library.component.spec.ts
  src/app/modules/library/home-page-project-library/home-page-project-library.component.ts
  src/app/modules/library/library-filters/library-filters.component.spec.ts
  src/app/modules/library/library-filters/library-filters.component.ts
  src/app/modules/library/library/library.component.ts
  src/app/modules/library/official-library/official-library.component.spec.ts
  src/app/modules/library/personal-library/personal-library.component.spec.ts
  src/app/modules/library/personal-library/personal-library.component.ts
  src/app/modules/library/public-library/public-library.component.html
  src/app/modules/library/public-library/public-library.component.spec.ts
  src/app/modules/library/public-library/public-library.component.ts
  src/app/modules/library/public-unit-type-selector/public-unit-type-selector.component.spec.ts
  src/app/modules/library/public-unit-type-selector/public-unit-type-selector.component.ts
  src/app/modules/library/teacher-project-library/teacher-project-library.component.spec.ts
  src/app/modules/library/teacher-project-library/teacher-project-library.component.ts
  src/app/services/library.service.ts
  src/messages.xlf
Labels: Code Quality

#2157 build(Application): Only generate messages if tests pass
  .github/workflows/develop-workflows.yml
  .github/workflows/other-branch-workflows.yml
Labels: build
