Repository WISE-Community/WISE-Client, pull requests merged in 2025-02, with the labels that each got.

#2078 refactor(ExportItemComponent): Convert to standalone and refactor
  src/assets/wise5/classroomMonitor/dataExport/data-export.module.ts
  src/assets/wise5/classroomMonitor/dataExport/export-item/export-item.component.html
  src/assets/wise5/classroomMonitor/dataExport/export-item/export-item.component.spec.ts
  src/assets/wise5/classroomMonitor/dataExport/export-item/export-item.component.ts
  src/assets/wise5/classroomMonitor/dataExport/strategies/AbstractComponentDataExportStrategy.ts
  src/messages.xlf
Labels: Code Quality

#2079 fix(CRater): Responses without ideas are throwing NPE
  src/assets/wise5/services/cRaterService.ts
Labels: enhancement

#2084 refactor(DialogGuidanceComponentDataExportStrategy): Simplify code
  src/assets/wise5/classroomMonitor/dataExport/strategies/DialogGuidanceComponentDataExportStrategy.ts
Labels: Code Quality

#2072 feat(DialogGuidance): Show detected ideas in teacher tools
  src/app/services/cRaterService.spec.ts
  src/assets/wise5/classroomMonitor/dataExport/strategies/DialogGuidanceComponentDataExportStrategy.spec.ts
  src/assets/wise5/components/common/cRater/CRaterIdea.ts
  src/assets/wise5/components/common/cRater/CRaterRubric.spec.ts
  src/assets/wise5/components/common/cRater/CRaterRubric.ts
  src/assets/wise5/components/dialogGuidance/detected-ideas/detected-ideas.component.html
  src/assets/wise5/components/dialogGuidance/detected-ideas/detected-ideas.component.scss
  src/assets/wise5/components/dialogGuidance/detected-ideas/detected-ideas.component.spec.ts
  src/assets/wise5/components/dialogGuidance/detected-ideas/detected-ideas.component.ts
  src/assets/wise5/components/dialogGuidance/dialog-guidance-grading/dialog-guidance-grading.component.html
  src/assets/wise5/components/dialogGuidance/dialog-guidance-grading/dialog-guidance-grading.component.ts
  src/assets/wise5/components/dialogGuidance/dialog-guidance-show-work/dialog-guidance-show-work.component.spec.ts
  src/assets/wise5/components/dialogGuidance/dialog-guidance-show-work/dialog-guidance-show-work.component.ts
  src/assets/wise5/components/dialogGuidance/dialog-responses/dialog-responses.component.html
  src/assets/wise5/components/dialogGuidance/dialog-responses/dialog-responses.component.scss
  src/assets/wise5/components/dialogGuidance/dialog-responses/dialog-responses.component.ts
  src/assets/wise5/components/match/match-student/match-student-default/match-student-default.component.ts
  src/messages.xlf
Labels: enhancement, 16 points

#2086 refactor(ShowStudentInfoComponent): Convert to standalone
  src/assets/wise5/classroomMonitor/classroomMonitorComponents/manageStudents/manage-students.module.ts
  src/assets/wise5/classroomMonitor/classroomMonitorComponents/manageStudents/show-student-info/show-student-info.component.html
  src/assets/wise5/classroomMonitor/classroomMonitorComponents/manageStudents/show-student-info/show-student-info.component.scss
  src/assets/wise5/classroomMonitor/classroomMonitorComponents/manageStudents/show-student-info/show-student-info.component.spec.ts
  src/assets/wise5/classroomMonitor/classroomMonitorComponents/manageStudents/show-student-info/show-student-info.component.ts
  src/messages.xlf
Labels: Code Quality

#2081 feat(MatchComponentDataExportStrategy): Include ideas detected by C-Rater
  src/assets/wise5/classroomMonitor/dataExport/strategies/AbstractComponentDataExportStrategy.ts
  src/assets/wise5/classroomMonitor/dataExport/strategies/MatchComponentDataExportStrategy.spec.ts
  src/assets/wise5/classroomMonitor/dataExport/strategies/MatchComponentDataExportStrategy.ts
Labels: enhancement

#2076 feat(DialogGuidance): Allow authors specify text for ideas
  src/app/authoring-tool/edit-component-advanced/edit-component-advanced.component.html
  src/app/teacher/component-authoring.module.ts
  src/assets/wise5/components/common/cRater/edit-crater-idea-descriptions/edit-crater-idea-descriptions.component.html
  src/assets/wise5/components/common/cRater/edit-crater-idea-descriptions/edit-crater-idea-descriptions.component.scss
  src/assets/wise5/components/common/cRater/edit-crater-idea-descriptions/edit-crater-idea-descriptions.component.ts
  src/assets/wise5/components/common/feedbackRule/edit-feedback-rules/edit-feedback-rules.component.ts
  src/assets/wise5/components/dialogGuidance/dialog-guidance-authoring/dialog-guidance-authoring.component.ts
  src/assets/wise5/components/dialogGuidance/dialogGuidanceService.ts
  src/assets/wise5/components/dialogGuidance/edit-dialog-guidance-advanced/edit-dialog-guidance-advanced.component.html
  src/assets/wise5/components/dialogGuidance/edit-dialog-guidance-advanced/edit-dialog-guidance-advanced.component.ts
  src/messages.xlf
Labels: enhancement

#2082 refactor(MatchStudentDefault): Convert to standalone
  src/assets/wise5/components/match/match-student/match-student-choice-reuse/match-student-choice-reuse.ts
  src/assets/wise5/components/match/match-student/match-student-default/match-student-default.component.html
  src/assets/wise5/components/match/match-student/match-student-default/match-student-default.component.spec.ts
  src/assets/wise5/components/match/match-student/match-student-default/match-student-default.component.ts
  src/assets/wise5/components/match/match-student/match-student.component.ts
  src/assets/wise5/components/match/match-student/match-student.module.ts
  src/messages.xlf
Labels: Code Quality

#2091 refactor(ManageUserComponent): Convert to standalone
  src/assets/wise5/classroomMonitor/classroomMonitorComponents/manageStudents/manage-students.module.ts
  src/assets/wise5/classroomMonitor/classroomMonitorComponents/manageStudents/manage-user/manage-user.component.html
  src/assets/wise5/classroomMonitor/classroomMonitorComponents/manageStudents/manage-user/manage-user.component.spec.ts
  src/assets/wise5/classroomMonitor/classroomMonitorComponents/manageStudents/manage-user/manage-user.component.ts
  src/messages.xlf
Labels: Code Quality

#2095 refactor(MatchStudentChoiceReuse): Convert to standalone
  src/assets/wise5/components/match/match-student/match-student-choice-reuse/match-student-choice-reuse.component.ts
  src/assets/wise5/components/match/match-student/match-student-choice-reuse/match-student-choice-reuse.ts
  src/assets/wise5/components/match/match-student/match-student.component.ts
  src/assets/wise5/components/match/match-student/match-student.module.ts
Labels: Code Quality

#2096 refactor(LabelShowWorkComponent): Convert to standalone
  src/app/teacher/component-show-work.module.ts
  src/assets/wise5/components/label/label-grading/label-grading.module.ts
  src/assets/wise5/components/label/label-show-work/label-show-work.component.ts
  src/assets/wise5/components/label/label-show-work/label-show-work.module.ts
  src/assets/wise5/components/showWork/show-work-student/show-work-student.module.ts
Labels: Code Quality

#2098 refactor(ManageTeamComponent): Convert to standalone
  src/assets/wise5/classroomMonitor/classroomMonitorComponents/manageStudents/manage-students.module.ts
  src/assets/wise5/classroomMonitor/classroomMonitorComponents/manageStudents/manage-team/manage-team.component.html
  src/assets/wise5/classroomMonitor/classroomMonitorComponents/manageStudents/manage-team/manage-team.component.spec.ts
  src/assets/wise5/classroomMonitor/classroomMonitorComponents/manageStudents/manage-team/manage-team.component.ts
  src/assets/wise5/classroomMonitor/classroomMonitorComponents/manageStudents/manage-user/manage-user.component.ts
  src/messages.xlf
Labels: Code Quality

#2097 refactor(SummaryDisplay): Move methods to child classes
  src/app/domain/dummyComponentState.ts
  src/assets/wise5/common/DummyAnnotation.ts
  src/assets/wise5/directives/student-summary-display/student-summary-display.component.spec.ts
  src/assets/wise5/directives/student-summary-display/student-summary-display.component.ts
  src/assets/wise5/directives/summary-display/summary-display.component.ts
  src/assets/wise5/directives/teacher-summary-display/teacher-summary-display.component.ts
  src/messages.xlf
Labels: Code Quality

#2100 refactor(SummaryDisplay): Created class for series data
  src/assets/wise5/common/SeriesData.ts
  src/assets/wise5/common/SeriesDataPoint.ts
  src/assets/wise5/directives/student-summary-display/student-summary-display.component.ts
  src/assets/wise5/directives/summary-display/summary-display.component.ts
Labels: Code Quality
