Repository WISE-Community/WISE-Client, pull requests merged in 2025-01, with the labels that each got.

#2030 refactor(StudentGradingToolsComponent): convert to standalone
  src/app/teacher/classroom-monitor.module.ts
  src/assets/wise5/classroomMonitor/classroomMonitorComponents/shared/tool-bar/tool-bar.component.html
  src/assets/wise5/classroomMonitor/classroomMonitorComponents/studentGrading/student-grading-tools/student-grading-tools.component.html
  src/assets/wise5/classroomMonitor/classroomMonitorComponents/studentGrading/student-grading-tools/student-grading-tools.component.spec.ts
  src/assets/wise5/classroomMonitor/classroomMonitorComponents/studentGrading/student-grading-tools/student-grading-tools.component.ts
  src/messages.xlf
Labels: Code Quality

#2031 refactor(ToolBarComponent): convert to standalone
  package-lock.json
  package.json
  src/app/teacher/classroom-monitor.module.ts
  src/assets/wise5/classroomMonitor/classroom-monitor.component.html
  src/assets/wise5/classroomMonitor/classroomMonitorComponents/shared/tool-bar/tool-bar.component.html
  src/assets/wise5/classroomMonitor/classroomMonitorComponents/shared/tool-bar/tool-bar.component.spec.ts
  src/assets/wise5/classroomMonitor/classroomMonitorComponents/shared/tool-bar/tool-bar.component.ts
  src/messages.xlf
Labels: Code Quality

#2032 refactor(SideMenuComponent): convert to standalone
  src/app/student-teacher-common.module.ts
  src/app/teacher/authoring-tool.module.ts
  src/app/teacher/classroom-monitor.module.ts
  src/assets/wise5/authoringTool/authoring-tool.component.html
  src/assets/wise5/classroomMonitor/classroom-monitor.component.html
  src/assets/wise5/common/main-menu/main-menu.component.ts
  src/assets/wise5/common/side-menu/side-menu.component.html
  src/assets/wise5/common/side-menu/side-menu.component.spec.ts
  src/assets/wise5/common/side-menu/side-menu.component.ts
Labels: Code Quality

#2033 refactor(MainMenuComponent): convert to standalone
  src/app/student-teacher-common.module.ts
  src/app/teacher/authoring-tool.module.ts
  src/app/teacher/classroom-monitor.module.ts
  src/assets/wise5/classroomMonitor/classroom-monitor.component.html
  src/assets/wise5/common/main-menu/main-menu.component.html
  src/assets/wise5/common/main-menu/main-menu.component.spec.ts
  src/assets/wise5/common/main-menu/main-menu.component.ts
  src/assets/wise5/common/side-menu/side-menu.component.ts
  src/messages.xlf
Labels: Code Quality

#2034 refactor(NotificationService): remove server connection status handling
  src/assets/wise5/classroomMonitor/classroom-monitor.component.ts
  src/assets/wise5/services/httpInterceptor.js
  src/assets/wise5/services/notificationService.ts
  src/messages.xlf
Labels: Code Quality

#2037 refactor(ClassroomMonitorComponent): convert to standalone
  src/app/teacher/classroom-monitor.module.ts
  src/assets/wise5/classroomMonitor/classroom-monitor.component.html
  src/assets/wise5/classroomMonitor/classroom-monitor.component.spec.ts
  src/assets/wise5/classroomMonitor/classroom-monitor.component.ts
  src/messages.xlf
Labels: Code Quality

#2036 feat(LibraryFiltersComponent): add research project filtering functionality
  src/app/domain/projectFilterValues.ts
  src/app/modules/library/library-filters/library-filters.component.html
  src/app/modules/library/library-filters/library-filters.component.ts
  src/app/modules/library/library/library.component.ts
  src/app/modules/library/personal-library/personal-library.component.spec.ts
  src/app/modules/library/standard.ts
  src/messages.xlf
Labels: 16 points

#2041 refactor(NavItemComponent): Convert to standalone
  src/app/teacher/classroom-monitor.module.ts
  src/assets/wise5/classroomMonitor/classroomMonitorComponents/nodeProgress/nav-item/nav-item.component.html
  src/assets/wise5/classroomMonitor/classroomMonitorComponents/nodeProgress/nav-item/nav-item.component.spec.ts
  src/assets/wise5/classroomMonitor/classroomMonitorComponents/nodeProgress/nav-item/nav-item.component.ts
  src/assets/wise5/classroomMonitor/classroomMonitorComponents/nodeProgress/node-progress-view/node-progress-view.component.html
  src/messages.xlf
Labels: Code Quality

#2040 refactor(MatchStudent): Simplify logic for better encapsulation
  src/assets/wise5/components/match/bucket.spec.ts
  src/assets/wise5/components/match/bucket.ts
  src/assets/wise5/components/match/choice.spec.ts
  src/assets/wise5/components/match/choice.ts
  src/assets/wise5/components/match/match-authoring/match-authoring.component.ts
  src/assets/wise5/components/match/match-student/match-student-choice-reuse/match-student-choice-reuse.ts
  src/assets/wise5/components/match/match-student/match-student-default/match-student-default.component.html
  src/assets/wise5/components/match/match-student/match-student-default/match-student-default.component.spec.ts
  src/assets/wise5/components/match/match-student/match-student-default/match-student-default.component.ts
  src/assets/wise5/components/match/matchService.ts
  src/messages.xlf
Labels: Code Quality

#2046 refactor(LibraryComponent): Simplify search and filter logic
  src/app/modules/library/library/library.component.ts
Labels: Code Quality

#2045 refactor(MatchFeedbackSection): Convert to standalone
  src/assets/wise5/components/match/match-common.module.ts
  src/assets/wise5/components/match/match-show-work/match-show-work.component.html
  src/assets/wise5/components/match/match-student/match-feedback-section/match-feedback-section.component.html
  src/assets/wise5/components/match/match-student/match-feedback-section/match-feedback-section.component.ts
  src/assets/wise5/components/match/match-student/match-student-default/match-student-default.component.html
  src/messages.xlf
Labels: Code Quality

#2052 refactor(MatchService): Simplify test setup and remove unused getItemById()
  src/app/services/matchService.spec.ts
  src/assets/wise5/components/componentService.ts
  src/assets/wise5/components/match/matchService.ts
Labels: Code Quality

#2048 refactor(MatchStatusIcon): Convert to standalone
  src/assets/wise5/components/match/match-choice-item/match-choice-item.component.html
  src/assets/wise5/components/match/match-common.module.ts
  src/assets/wise5/components/match/match-status-icon/match-status-icon.component.html
  src/assets/wise5/components/match/match-status-icon/match-status-icon.component.ts
  src/messages.xlf
Labels: Code Quality

#2053 refactor(AddChoiceButton): Convert to standalone
  src/assets/wise5/components/match/match-student/add-choice-button/add-choice-button.component.html
  src/assets/wise5/components/match/match-student/add-choice-button/add-choice-button.component.ts
  src/assets/wise5/components/match/match-student/match-student-default/match-student-default.component.html
  src/assets/wise5/components/match/match-student/match-student.module.ts
  src/messages.xlf
Labels: Code Quality

#2060 refactor(LabelStudentComponent): Convert to standalone
  src/assets/wise5/components/Components.ts
  src/assets/wise5/components/component/component-student.module.ts
  src/assets/wise5/components/label/label-student/label-student.component.html
  src/assets/wise5/components/label/label-student/label-student.component.spec.ts
  src/assets/wise5/components/label/label-student/label-student.component.ts
  src/assets/wise5/components/label/label-student/label-student.module.ts
  src/messages.xlf
Labels: Code Quality

#2057 refactor(AddMatchChoiceDialogue): Convert to standalone
  src/assets/wise5/components/match/match-student/add-match-choice-dialog/add-match-choice-dialog.html
  src/assets/wise5/components/match/match-student/add-match-choice-dialog/add-match-choice-dialog.ts
  src/assets/wise5/components/match/match-student/match-student-default/match-student-default.component.ts
  src/assets/wise5/components/match/match-student/match-student.module.ts
  src/messages.xlf
Labels: Code Quality

#2054 feat(MatchStudent): import ideas detected in Dialog Guidance as choices
  src/app/services/cRaterService.spec.ts
  src/assets/wise5/common/ComponentContent.ts
  src/assets/wise5/components/common/cRater/CRaterIdea.ts
  src/assets/wise5/components/common/cRater/CRaterRubric.ts
  src/assets/wise5/components/match/edit-match-advanced/edit-match-advanced.component.ts
  src/assets/wise5/components/match/match-student/match-student-default/match-student-default.component.spec.ts
  src/assets/wise5/components/match/match-student/match-student-default/match-student-default.component.ts
  src/assets/wise5/services/cRaterService.ts
  src/messages.xlf
Labels: enhancement, 32 points

#2064 refactor(DialogResponseComponent): convert to standalone component
  src/app/student-teacher-common.module.ts
  src/assets/wise5/components/dialogGuidance/dialog-response/dialog-response.component.html
  src/assets/wise5/components/dialogGuidance/dialog-response/dialog-response.component.spec.ts
  src/assets/wise5/components/dialogGuidance/dialog-response/dialog-response.component.ts
  src/messages.xlf
Labels: Code Quality

#2059 style(Import Component): Use same UI/UX flow as Import Step
  src/app/authoring-tool/import-step/choose-import-step/choose-import-step.component.html
  src/app/authoring-tool/import-step/choose-import-unit/choose-import-unit.component.html
  src/app/authoring-tool/import-step/choose-import-unit/choose-import-unit.component.ts
  src/app/teacher/authoring-routing.module.ts
  src/app/teacher/authoring-tool.module.ts
  src/assets/wise5/authoringTool/importComponent/choose-import-component/choose-import-component.component.html
  src/assets/wise5/authoringTool/importComponent/choose-import-component/choose-import-component.component.spec.ts
  src/assets/wise5/authoringTool/importComponent/choose-import-component/choose-import-component.component.ts
  src/assets/wise5/authoringTool/importComponent/import-component-module.ts
  src/assets/wise5/authoringTool/node/add-component-button/add-component-button.component.ts
  src/messages.xlf
Labels: enhancement

#2058 refactor(DeleteChoiceButton): Convert to standalone
  src/assets/wise5/components/match/delete-choice-button/delete-choice-button.component.html
  src/assets/wise5/components/match/delete-choice-button/delete-choice-button.component.scss
  src/assets/wise5/components/match/delete-choice-button/delete-choice-button.component.spec.ts
  src/assets/wise5/components/match/delete-choice-button/delete-choice-button.component.ts
  src/assets/wise5/components/match/match-choice-item/match-choice-item.component.html
  src/assets/wise5/components/match/match-choice-item/match-choice-item.component.scss
  src/assets/wise5/components/match/match-common.module.ts
  src/messages.xlf
Labels: Code Quality

#2068 refactor(DialogGuidanceShowWorkComponent): convert to standalone
  src/app/teacher/component-show-work.module.ts
  src/assets/wise5/components/dialogGuidance/dialog-guidance-grading/dialog-guidance-grading.component.html
  src/assets/wise5/components/dialogGuidance/dialog-guidance-grading/dialog-guidance-grading.module.ts
  src/assets/wise5/components/dialogGuidance/dialog-guidance-show-work/dialog-guidance-show-work.component.html
  src/assets/wise5/components/dialogGuidance/dialog-guidance-show-work/dialog-guidance-show-work.component.spec.ts
  src/assets/wise5/components/dialogGuidance/dialog-guidance-show-work/dialog-guidance-show-work.component.ts
  src/assets/wise5/components/dialogGuidance/dialog-guidance-show-work/dialog-guidance-show-work.module.ts
  src/assets/wise5/components/showWork/show-work-student/show-work-student.component.html
  src/assets/wise5/components/showWork/show-work-student/show-work-student.module.ts
Labels: Code Quality

#2066 refactor(MatchAuthoring): Convert to standalone
  src/app/teacher/component-authoring.module.ts
  src/assets/wise5/components/Components.ts
  src/assets/wise5/components/match/match-authoring/match-authoring.component.html
  src/assets/wise5/components/match/match-authoring/match-authoring.component.ts
  src/messages.xlf
Labels: Code Quality

#2069 refactor(DialogGuidanceGrading): Remove DialogGuidanceGradingModule
  src/assets/wise5/classroomMonitor/classroomMonitorComponents/component-grading.component.ts
  src/assets/wise5/components/dialogGuidance/dialog-guidance-grading/dialog-guidance-grading.component.html
  src/assets/wise5/components/dialogGuidance/dialog-guidance-grading/dialog-guidance-grading.component.ts
  src/assets/wise5/components/dialogGuidance/dialog-guidance-grading/dialog-guidance-grading.module.ts
  src/messages.xlf
Labels: Code Quality

#2070 style(StudentProgressComponent): Fix issue where student row was not extending to the end
  src/assets/wise5/classroomMonitor/student-progress/student-progress.component.html
Labels: bug

#2062 refactor(LabelStudentComponent): Clean up code
  src/app/services/labelService.spec.ts
  src/assets/wise5/components/label/LabelStudentData.ts
  src/assets/wise5/components/label/label-student/label-student.component.html
  src/assets/wise5/components/label/label-student/label-student.component.spec.ts
  src/assets/wise5/components/label/label-student/label-student.component.ts
  src/assets/wise5/components/label/label.spec.ts
  src/assets/wise5/components/label/label.ts
  src/assets/wise5/components/label/labelService.ts
  src/messages.xlf
Labels: Code Quality

#2073 refactor(MatchChoiceItem): Convert to standalone (2nd try)
  src/assets/wise5/components/match/delete-choice-button/delete-choice-button.component.spec.ts
  src/assets/wise5/components/match/delete-choice-button/delete-choice-button.component.ts
  src/assets/wise5/components/match/match-choice-item/match-choice-item.component.html
  src/assets/wise5/components/match/match-choice-item/match-choice-item.component.ts
  src/assets/wise5/components/match/match-common.module.ts
  src/assets/wise5/components/match/match-show-work/match-show-work.component.html
  src/assets/wise5/components/match/match-student/match-student-default/match-student-default.component.html
  src/messages.xlf
Labels: Code Quality

#2075 refactor(MatchShowWorkComponent): Convert to standalone
  src/app/teacher/component-show-work.module.ts
  src/assets/wise5/components/match/match-grading/match-grading.component.html
  src/assets/wise5/components/match/match-grading/match-grading.module.ts
  src/assets/wise5/components/match/match-show-work/match-show-work-module.ts
  src/assets/wise5/components/match/match-show-work/match-show-work.component.html
  src/assets/wise5/components/match/match-show-work/match-show-work.component.ts
  src/assets/wise5/components/showWork/show-work-student/show-work-student.component.html
  src/assets/wise5/components/showWork/show-work-student/show-work-student.module.ts
Labels: Code Quality
